textlint/textlint

docs/create-rules.md
lib/config/config.js
lib/options.js
lib/rule/rule-manager.js
lib/textlint-engine.js
package.json
test/textlint-engine-test.js

textlint rule naming

---

lib/textlint-engine.js

resolve path with context if passed

---

src/rule/rule-manager.js
src/textlint-core.js
src/textlint-engine.js
test/textlint-core-test.js
test/textlint-engine-test.js

textlint-core has a instance of RuleManager
close #30

refactor(rule): change rule-manager to a class

---

src/textlint.js

EventEmitter memory leak detected

---

.jscsrc
docs/plugin.md
package.json
src/config/config.js
src/plugins/markdown/MarkdownProcessor.js
src/plugins/proccesor-helper.js
src/plugins/text/TextProcessor.js
src/rule/rule-context.js
src/textlint-core.js
src/textlint-engine.js
src/util/traverse.js
test/fixtures/test.unknown
test/textlint-engine-test.js
test/textlint-test.js
typing/textlint.d.ts

Plugins's Processor is for pre/post processing text.
Add before action and after action to linting text.
#37

feat(plugin): introduce Plugin's Processor

---

docs/use-as-modules.md
src/index.js
test/textlint-core-test.js

[PR] Expose TextLintCore

---

README.md
docs/configuring.md
src/rule/rule-context.js
src/textlint-core.js
test/config-test.js
test/textlint-core-test.js
test/textlint-test.js

feat(rule): implement warning of rule

---

src/rule/rule-context.js
test/textlint-core-test.js

default severity is `error`.
#44

fix(rule): default severity is error

---

src/textlint-core.js
src/textlint.js

Curve out functions for `RuleContext` from `TextLintCore` into `RuleContextDelegator`.

Refactor textlint-core

---

src/textlint-core.js
src/textlint-engine.js
test/pluguins/HTMLProcessor-test.js

Core has Processor instances
#52

refactor(core): engine not have Processor

---

docs/plugin.md

docs(plugin): add Plugin Processor

---

package.json
perf/.textlintrc
perf/README.md
perf/md/Connect.md
perf/md/ESLint.md
perf/md/comments.md
perf/md/creation.md
perf/md/declare.md
perf/md/delete.md
perf/md/enumeration.md
perf/md/equality.md
perf/md/global_footprint.md
perf/md/gulp.md
perf/md/higher_order.md
perf/md/jquery.md
perf/md/mutable.md
perf/md/properties.md
perf/md/prototype.md
perf/md/reference.md
perf/md/types.md
perf/md/variables.md
perf/package.json
perf/perf.js
perf/prh.yml
src/options.js

feat(perf): add performance test

---

README.md
docs/create-rules.md
src/textlint-core.js
src/util/timing.js

Per-rule Performance `TIMING=1`

---

src/config/config.js
src/config/plugin-loader.js
src/textlint-engine.js

fix(config): correct merging options and textlintrc options

---

src/config/config.js
src/config/plugin-loader.js
test/config-test.js
test/fixtures/plugin.textlintrc
test/fixtures/plugins/configurable-plugin/index.js
test/rule-manager-test.js

plugins's rulesConfig should be  "<plugins>/<rule-name>" : true | false | object
close #71

fix(plugin): set set plugins's config to "<plugin>/<rule>"

---

bin/textlint.js
package.json
perf/README.md
perf/run.js
src/cli.js
src/rule/rule-context-agent.js
src/textlint-core.js
src/textlint-engine.js
test/async-rule-test.js
test/cli-test.js
test/fixtures/rules/async-rule.js
test/fixtures/test.md
test/no-todo-test.js
test/pluguins/HTMLProcessor-test.js
test/rule-context-test.js
test/textlint-core-test.js
test/textlint-engine-test.js
test/textlint-test.js

Proof of concept for #74 
- support async rule
- return promise
- change lint* API to handle Promise
e.g.)
```js
export default function(context){
let {Syntax, getSource, RuleError, report} = context;
return {
[Syntax.ListItem](node) {
var text = getSource(node);
// async
return new Promise((resolve, reject) => {
setTimeout(function () {
if (/\[\s+\]\s/i.test(text)) {
report(node, new RuleError("found TODO: '" + text + "'"));
}
resolve();
}, 4000);
});
}
};
}
```
before commit(base)
```
Performance Run #1:  3312.270223ms
Performance Run #2:  3249.653642ms
Performance Run #3:  3317.800996ms
Performance Run #4:  3089.440099ms
Performance Run #5:  3133.880919ms
Performance budget ok:  3249.653642ms (limit: 3260.8695652173915ms)
```

async support

---

package.json
src/config/config-loader.js
src/config/plugin-loader.js
src/rule/load-rules.js
src/textlint-engine.js
test/fixtures/rules/issue81/no-default-assign-rule.js
test/textlint-engine-test.js

fix: use interop-require instead of require for dynamic loading

---

README.md
examples/html-plugin/.textlintrc
examples/html-plugin/README.md
examples/html-plugin/index.html
examples/html-plugin/package.json
package.json
src/config/plugin-loader.js
src/textlint-core.js
src/textlint-engine.js
test/example-test.sh
test/textlint-engine-test.js

Make HTML plugin opt-in

---

package.json
test/rule-context-test.js
test/textlint-core-test.js

<del>Lint API should start asynchronously.</del>
fix some async test

Fix Async Test

---

.travis.yml
src/textlint-core.js

fix error on Node.js 0.12

---

.eslintrc.js
docs/create-rules.md

docs: Add RuleError

---

README.md

chore(readme): add logo

---

README.md

- add link to http://textlint.github.io/
- add summary of textlint's features

docs(readme): add online demo link

---

README.md
docs/.textlintrc
docs/README.md
docs/getting-started.md

docs: add Getting Started

---

bin/textlint.js
package.json
src/cli.js
src/config/config-initializer.js
src/options.js
test/config-initializer-test.js

with `--init` option, generate .textlintrc file if not existed.

add --init option like eslint.

---

README.md
docs/getting-started.md

Add document about --init #129

docs(cli): usage of --init

---

package.json
src/textlint-core-task.js
test/cli-test.js

This Pull Request fix following warning messages.
```
(node) warning: possible EventEmitter memory leak detected. 11 Str listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at RuleTypeEmitter.addListener (events.js:239:17)
at /Users/azu/.ghq/github.com/azu/JavaScript-Plugin-Architecture/node_modules/textlint/lib/textlint-core-task.js:141:40
at Array.forEach (native)
at TextLintCoreTask._addListenRule (/Users/azu/.ghq/github.com/azu/JavaScript-Plugin-Architecture/node_modules/textlint/lib/textlint-core-task.js:140:31)
at /Users/azu/.ghq/github.com/azu/JavaScript-Plugin-Architecture/node_modules/textlint/lib/textlint-core-task.js:126:28
at Array.forEach (native)
at TextLintCoreTask._setupRuleCreatorListener (/Users/azu/.ghq/github.com/azu/JavaScript-Plugin-Architecture/no …
```

Fix event emitter memory leak detected

---

package.json

refactor(npm): use npm-run-all

---

.editorconfig
CONTRIBUTING.md
docs/getting-started.md
package.json

fix #110
Welcome to CONTRIBUTE!

Add CONTRIBUTING.md

---

package.json
src/cli.js
src/fixer/formatters/stylish.js
src/fixer/textfix-formatter.js
src/fixer/textlint-fixer.js
test/fixer/formatters/stylish-test.js

feat(fixer): add fixable stylish formatter

---

docs/README.md
docs/faq/line-column-or-index.md
src/core/source-location.js

docs(faq): add faq about usage of index

---

docs/README.md
docs/faq/failed-to-load-textlints-module.md
docs/faq/line-column-or-index.md
src/core/source-location.js
src/engine/textlint-module-resolver.js
test/textlint-module-resolver-test.js

> Failed to load textlint's rule module: "${packageName}" is not found.
See FAQ: https://github.com/textlint/textlint/blob/master/docs/faq/failed-to-load-textlints-module.md

docs(FAQ): failed to load modules

---

src/cli.js
src/options.js

Remove `throwWithoutExperimental` from --fix
ref #145

feat(fixer): --fix to be stable

---

README.md

Add URL of @io-monad's chrome extension.

chore(readme): add chrome extension

---

test/config-fixtures/js-config/.textlintrc
test/config-fixtures/js-config/expect.json
test/config-fixtures/js-config/modules/textlint-rule-a.js
test/config-fixtures/js-config/modules/textlint-rule-b.js
test/config-fixtures/js-config/modules/textlint-rule-c.js
test/config-fixtures/yaml/.textlintrc
test/config-fixtures/yaml/expect.json
test/config-fixtures/yaml/modules/textlint-rule-a.js
test/config-fixtures/yaml/modules/textlint-rule-b.js
test/config-fixtures/yaml/modules/textlint-rule-c.js

test(config): add js config and yaml config tests

---

docs/formatter.md
src/fixer/fixer-processor.js
test/textlint-core-fixer-test.js
typing/textlint.d.ts

Breaking Change: rename originalMessages to messsages

---

typings/textlint.d.ts

feat(d.ts): Add TextLintRuleContext to textlint.d.ts 

---

README.md

Ref https://github.com/scrooloose/syntastic/issues/1730

docs(readme): add vim integration using syntastic

---

src/fixer/fixer-processor.js
src/linter/linter-processor.js
src/util/sort-messages.js
test/sort-message-test.js

feat(core):  sort messages by line and column

---

docs/configuring.md
src/config/config-loader.js
src/config/config.js
src/config/preset-loader.js
src/engine/textlint-module-resolver.js
test/config-loader-test.js
test/fixtures/config-loader/.textlintrc
test/fixtures/config-loader/@textlint/textlint-config-example/index.js
test/fixtures/config-loader/@textlint/textlint-config-example/package.json
test/fixtures/config-loader/alt-textlintrc
test/fixtures/engine/textlint-module-resolver/@textlint/textlint-config-example/index.js
test/fixtures/engine/textlint-module-resolver/@textlint/textlint-config-example/package.json
test/fixtures/engine/textlint-module-resolver/config.js
test/textlint-module-resolver-test.js
typings/textlint.d.ts

implement #47 
```
textlint --config <config-module>
textlint --config textlint-config-<name>
textlint --config @textlint/textlint-config
```

feat(config): support sharable config 

---

src/textlint-core.js
src/util/fs-promise.js
test/rule-context/rule-context-test.js

feat(core): always start asynchronous

---

docs/rule.md
docs/txtnode.md
src/README.md
src/core/source-code.js
src/index.js
src/shared/type/MessageType.js
src/shared/type/NodeType.js
src/shared/type/SeverityLevel.js

feat(index): expose Constants Types

---

.github/ISSUE_TEMPLATE.md
README.md
bin/textlint.js
src/options.js

add Issue template

---

docs/rule.md
src/task/textlint-core-task.js

Ref https://github.com/textlint/textlint/issues/193
It is temporary change.
It will be revert in the future.

Experimental: add experimental flag to `shouldIgnore`

---

docs/txtnode.md
src/shared/type/TextLintNodeType.js

feat(node): add "Comment" type

---

package.json
src/core/rule-creator-helper.js
src/core/rule-creator-set.js
src/task/fixer-task.js
src/task/linter-task.js
src/task/textlint-core-task.js
test/RuleCreatorSet/RuleCreatorSet-test.js
test/textlint/textlint-test.js

It aim to implement the proposal: not load duplicated rule(ruleConfig) #219

refactor(core): refactoring core-task/linter-task/fixer task

---

README.md
docs/configuring.md
docs/filter-rule.md

- add configuration of filter rules
- add supress error to FAQ

docs(filter): add filter rules document

---

package.json

Upgrade remark https://github.com/textlint/markdown-to-ast/releases/tag/3.4.0
Free chokidar dependency. ⏩ Make installation fast.

feat(markdown): update textlint-plugin-markdown@1.1.0

---

.travis.yml
CONTRIBUTING.md
examples/cli/package.json
examples/config-file/package.json
examples/filter/package.json
examples/fix-dry-run/package.json
examples/fix/package.json
examples/html-plugin/package.json
examples/plugin/package.json
examples/rulesdir/package.json
examples/use-as-module/package.json
package.json

Use `yarn --mutex file` 
via https://github.com/yarnpkg/yarn/issues/1303#issuecomment-255758847

chore(test): use yarn --mutex file

---

.babelrc
package.json
src/config/config-initializer.js
test/other/no-todo-test.js
test/textlint-module-mapper/fixtures/configurable-plugin/index.js
test/textlint-module-mapper/textlint-module-mapper-test.js

use https://github.com/zertosh/babel-plugin-transform-inline-imports-commonjs

perf: improve speed by lazy loading module

---

docs/README.md
docs/rule-tips/after-all.md
packages/textlint/test/rule-tips/fixtures/rules/after-all.js
packages/textlint/test/rule-tips/rule-tips-after-all-test.js

docs(rule): How to implement "after-all" in the rule?

---

packages/textlint-plugin-markdown/package.json
packages/textlint-plugin-markdown/yarn.lock

BREAKING CHANGE: markdown-to-ast@4 includes some breaking change
#278

feat(textlint-plugin-markdown): update markdown-to-ast@^4

---

packages/textlint-kernel/src/TextlintKernelOptions.json
packages/textlint-kernel/src/core/rule-context.js
packages/textlint-kernel/src/fixer/fixer-processor.js
packages/textlint-kernel/src/linter/linter-processor.js
packages/textlint-kernel/src/task/fixer-task.js
packages/textlint-kernel/src/task/linter-task.js
packages/textlint-kernel/src/textlint-kernel.d.ts
packages/textlint-kernel/src/textlint-kernel.js
packages/textlint-kernel/tools/update-json-schema.js
packages/textlint/src/textlint-core.js
packages/textlint/test/rule-context/rule-context-test.js

feat(textlint-kernel): add `configBaseDir` option

---

packages/textlint-kernel/src/core/filter-rule-context.ts
packages/textlint-kernel/src/core/rule-context.ts
packages/textlint-kernel/src/task/fixer-task.ts
packages/textlint-kernel/src/task/linter-task.ts

fix(kernel): remove `RuleContext#config`

---

lerna.json

chore(lerna): no more concurrency limit

---

.travis.yml

chore(travis): cache yarn again

---

packages/textlint-kernel/src/core/rule-context.ts
packages/textlint/test/rule-context/rule-context-test.js

fix(kernel): assert 3rd argument on `report` function

---

packages/textlint-kernel/package.json

Remove `carrack` module.
Closes #331

refactor(kernel): remove unused dependency

---

.github/CONTRIBUTING.md

Closes #351 
Please review this PR !

docs(CONTRIBUTING): Add guide for beginner

---

README.md

docs(README): Fix broken links

---

packages/textlint-formatter/bin/cmd.js
packages/textlint-formatter/test/fixtures/myfile.js
packages/textlint-formatter/test/formatters/checkstyle.js
packages/textlint-formatter/test/formatters/compact.js
packages/textlint-formatter/test/formatters/jslint-xml.js
packages/textlint-formatter/test/formatters/json.js
packages/textlint-formatter/test/formatters/junit.js
packages/textlint-formatter/test/formatters/pretty-error-test.js
packages/textlint-formatter/test/formatters/stylish.js
packages/textlint-formatter/test/formatters/table.js
packages/textlint-formatter/test/formatters/tap.js
packages/textlint-formatter/test/formatters/unix.js
packages/textlint-formatter/test/textlint-formatter-test.js

refactor(textlint-formatter): apply prettier

---

packages/textlint/package.json

Move from devDepencies to depndenvies
Followup #347 #365

fix(textlint): move textlint-fixer-formatter from devDeps to deps

---

packages/@textlint/ast-node-types/src/TextLintASTNodeTypes.ts
packages/@textlint/kernel/src/core/BaseRuleContext.ts
packages/@textlint/kernel/src/core/filter-rule-context.ts
packages/@textlint/kernel/src/core/rule-context.ts
packages/@textlint/kernel/src/core/rule-creator-helper.ts
packages/@textlint/kernel/src/index.ts
packages/@textlint/kernel/src/shared/rule-severity.ts
packages/@textlint/kernel/src/task/textlint-core-task.ts
packages/@textlint/kernel/src/textlint-kernel-interface.ts
packages/@textlint/kernel/test/helper/ErrorRule.ts

refactor(kernel): export actual rule/filter rule/plugin interface

---

README.md
packages/@textlint/kernel/src/textlint-kernel-interface.ts
packages/@textlint/kernel/test/helper/ErrorRule.ts

Fix kernel test that is failed.

fix(textlint): fix kernel test

---

docs/getting-started.md

fix(getting-started): fix broken link

---

.github/ISSUE_TEMPLATE.md

Correct link in the GitHub issue template. Closes #379.

doc(ISSUE_TEMPLATE): Correct link

---

packages/textlint/test/cli/cli-test.js

test(textlint): add tests for `textlint --version`

---

packages/textlint-formatter/test/textlint-formatter-test.js

Remove unnecessary `console.log`. Closes #391.

refactor(textlint-formatter): remove unnecessary logging

---

packages/textlint/src/cli.ts
packages/textlint/test/cli/cli-test.js

Also make a message more useful.
Fixes #406

Return an exit status when no rules found

---

packages/textlint-fixer-formatter/package.json
packages/textlint-fixer-formatter/src/index.ts
packages/textlint-fixer-formatter/test/textlint-fixer-formatter-test.js
packages/textlint-fixer-formatter/test/textlint-fixer-formatter-test.ts

Hi, could you review my preliminary `getFormatterList` implementation for `textlint-fixer-formatter`(#399)?

feat(textlint-fixer-formatter): add getFormatterList function

---

examples/use-as-ts-module/.gitignore
examples/use-as-ts-module/README.md
examples/use-as-ts-module/fixtures/failure.md
examples/use-as-ts-module/fixtures/success.md
examples/use-as-ts-module/package.json
examples/use-as-ts-module/src/index.ts
examples/use-as-ts-module/tsconfig.json

Hi, I created TypeScript example for your review.
Closes #350.

feat(example): add use-as-ts-module example

---

packages/@textlint/kernel/src/core/rule-context.ts
packages/@textlint/kernel/src/core/rule-error.ts
packages/@textlint/kernel/src/core/source-location.ts
packages/@textlint/kernel/src/fixer/rule-fixer.ts
packages/@textlint/kernel/src/task/textlint-core-task.ts
packages/@textlint/kernel/src/textlint-kernel-interface.ts
packages/@textlint/kernel/test/textlint-kernel-test.ts

 refactor(kernel): remove `isAbsolute` from `TextlintFixCommand` 

---

.travis.yml

Use npm@5 on CI

---

packages/@textlint/feature-flag/package.json
packages/@textlint/feature-flag/src/textlint-feature-flag.js
yarn.lock

fix(feature-flag): Update MapLike@2

---

packages/@textlint/kernel/package.json
packages/@textlint/kernel/src/core/filter-rule-context.ts
packages/@textlint/kernel/src/core/rule-context.ts
packages/@textlint/kernel/src/core/source-code.ts
packages/@textlint/kernel/test/source-code/source-code-test.ts
yarn.lock

`SourceCode#getSource` never return `null`.
Because, `this.text` always has value.

fix(kernel): fix return type of `SourceCode#getSource`

---

packages/@textlint/feature-flag/package.json
packages/markdown-to-ast/package.json
packages/textlint-ast-test/package.json
packages/textlint-plugin-markdown/package.json
packages/textlint-plugin-text/package.json
packages/textlint-tester/package.json
packages/txt-ast-traverse/package.json
packages/txt-to-ast/package.json

chore(yarn): add `clean` script to packages

---

package.json

Closes #421. @azu, since I cannot test `prepublish` on my end, please let me know if you have any issue while `publish`. Thank you.

chore(yarn): run `clean` before `test` and `publish`

---

README.md

Some edits here fix grammatical errors while others are just to make the english sound more idiomatic.
Thanks for all your work on this! Love the project.

Improves the english a bit in the readme

---

.github/CONTRIBUTING.md
.travis.yml
README.md
docs/.textlintrc
package.json
yarn.lock

Use textlint-rule-no-dead-link, update documents

---

README.md
docs/configuring.md

Fixed s/rc-loader/rc-config-loader

---

README.md
packages/markdown-to-ast/README.md
packages/textlint-ast-test/README.md
packages/txt-to-ast/README.md

- Remove unused badge
- Fix link

docs(packages): cleanup README.md

---

packages/@textlint/kernel/test/helper/ExamplePlugin.ts
packages/@textlint/kernel/test/kernel-plugin-test.ts

test(kernel): add tests for kernel plugin processor

---

docs/plugin.md
docs/rule-preset.md
docs/rule.md

Add "Publishing" section to rule, preset and plugin.
This section contains
- Package Naming Conventions
- (Rule) Naming Convetions
- Keywords

docs(publishing): add "Publishing" section

---

website/pages/en/help.js
website/sidebars.json

chore(website): add contribution guideline to help and side bar

---

packages/textlint-tester/package.json

fix https://github.com/textlint/textlint/issues/475

fix(tester): fix "main" and "types" field in package.json

---

.travis.yml
appveyor.yml

fix(test): update Travis and Appveyor setup

---

packages/@textlint/textlint-plugin-text/README.md
website/pages/en/index.js

A small follow-up pull request for #485 and #486. Will merge after successful CI builds as it is trivial changes.

Update links and markdown

---

packages/textlint-tester/README.md
packages/textlint-tester/package.json
packages/textlint-tester/src/textlint-tester.ts
packages/textlint-tester/test/textlint-tester-invalid-testcofig-test.js
packages/textlint-tester/test/textlint-tester-plugin.ts
yarn.lock

Closes #488. Please review. Thank you.

feat(textlint-tester): add multiple rules and plugins test support

---

examples/cli/package.json
examples/filter/package.json
examples/fix-dry-run/package.json
examples/fix/package.json
examples/html-plugin/package.json
examples/perf/package.json
examples/preset/package.json
examples/use-as-module/package.json
examples/use-as-ts-module/package.json
yarn.lock

For housekeeping. Please review.Thank you.

chore(examples): update dependencies

---

docs/CONTRIBUTING.md

First iteration for #472 still in progress. Appreciate any comments.
> 1. Merge part of README and Contributing Guideline
Will rebase on master and squash non–significant commits before merge.

docs(CONTRIBUTING): improve contribution guideline

---

docs/txtnode.md

I've defined minimal property
- Header
- Link
- Image
It will help to create textlint plugin like #116

docs(txtnode): add **MUST** and **SHOULD**

---

docs/CONTRIBUTING.md
packages/@textlint/markdown-to-ast/example/app/app.js
packages/textlint-tester/src/test-util.ts

https://seesparkbox.com/foundry/semantic_commit_messages throw error at sometimes.
Also, This article is duplicated with CONTRIBUTING.md
So, I've removed link.

fix(docs): fix flaky link

---

docs/configuring.md

- Add available extendsion like `.textlintrc.js`

docs(config): Add available extensions

---

packages/@textlint/ast-tester/.travis.yml
packages/@textlint/linter-formatter/.travis.yml

Remove travis.yml from packages directory

---

packages/textlint/src/config/config.ts
packages/textlint/src/options.ts
packages/textlint/test/config/config-as-example-test.js
packages/textlint/test/config/config-test.js

Support --no-textlintrc

---

website/siteConfig.js

現状textlintのwebsiteに掲載されている情報は古いので、変更しました。

change vuejs usecase

---

packages/textlint/src/cli.ts
packages/textlint/src/config/config-initializer.ts
packages/textlint/test/config-initializer/config-initializer-test.ts

fix #504 
- Show message if `textlint --init` is success
- Convert tests to TypeScript

feat(textlint): show message if `textlint --init` is success

---

.travis.yml

perf(travis): use bootstrap --scope for website jobs

---

packages/textlint/test/cli/cli-test.js

test(textlint): add cli output test

---

website/.textlintrc

https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks is something wrong.

docs(textlint): add ignore list

---

packages/textlint/src/cli.ts
packages/textlint/test/cli/cli-test.ts

I am new to TypeScript. Please let me know if something is wrong.
Ref: #369

refactor(textlint): convert cli tests to TypeScript

---

README.md
docs/integrations.md
docs/use-as-modules.md
website/i18n/en.json
website/package.json
website/sidebars.json
yarn.lock

Add "Integrating with Editors" page to website.

docs(website): add Integration Guide

---

packages/@textlint/textlint-plugin-markdown/package.json
packages/@textlint/textlint-plugin-markdown/test/MarkdownProcessor-test.js

- Depend on @textlint/kernel instead of textlint
Refs #567

refactor(textlint-plugin-markdown): remove cycle dependency

---

packages/@textlint/textlint-plugin-markdown/test/MarkdownProcessor-test.js
packages/@textlint/textlint-plugin-text/package.json
packages/@textlint/textlint-plugin-text/test/TextProcessor-test.js

refactor(textlint-plugin-text): Use @textlint/kernel instead of textlint

---

packages/@textlint/markdown-to-ast/package.json

refactor(markdown-to-ast): remove unused deps

---

.travis.yml

chore(travis): Move Documentation Test to "TEST" group

---

packages/gulp-textlint/package.json

chore(textlint): move dependencies.

---

packages/@textlint/fixer-formatter/src/index.ts
packages/@textlint/kernel/src/task/linter-task.ts
packages/@textlint/kernel/src/textlint-kernel.ts
packages/@textlint/linter-formatter/src/index.ts
packages/@textlint/types/src/Rule/TextlintRuleError.ts
packages/textlint/bin/textlint.js
packages/textlint/src/cli.ts
packages/textlint/src/engine/execute-file-backers/cache-backer.ts
packages/textlint/src/engine/textlint-engine-core.ts
packages/textlint/src/util/traverse.ts

fix(textlint): add reasonable debug log

---

README.md

Fix typo .textlinrc to .textlintrc

docs: update README.md (typo fixed)

---

appveyor.yml
packages/textlint/package.json
packages/textlint/test/config-initializer/fixtures/package.json
yarn.lock

chore(deps): update dependencies

---

README.md
package.json
packages/textlint/src/options.ts

fix(textlint): fix --rulesdir description

---

packages/@textlint/fixer-formatter/package.json
yarn.lock

It fix CVE alert.
3 https://github.com/kpdecker/jsdiff/blob/master/release-notes.md#v300---august-23rd-2016

chore(deps): update diff library

---

docs/rule-advanced.md
packages/@textlint/kernel/package.json
packages/@textlint/kernel/src/core/source-location.ts
packages/textlint/package.json
packages/textlint/src/config/config-initializer.ts
packages/textlint/src/config/config.ts
packages/textlint/src/config/preset-loader.ts
packages/textlint/src/textlint-core.ts

chore(deps): remove object-assign

---

examples/html-plugin/package.json
packages/@textlint/feature-flag/package.json
packages/@textlint/feature-flag/src/textlint-feature-flag.ts
packages/@textlint/feature-flag/test/mocha.opts
packages/@textlint/feature-flag/test/textlint-feature-flag-test.ts
packages/@textlint/feature-flag/test/tsconfig.json
packages/@textlint/feature-flag/tsconfig.json
packages/textlint/bin/textlint.js
packages/textlint/src/cli.ts
packages/textlint/src/engine/execute-file-backer-manager.ts
packages/textlint/src/engine/execute-file-backers/cache-backer.ts
packages/textlint/src/engine/textlint-module-loader.ts
packages/textlint/src/options.ts
packages/textlint/src/parallel/lint-worker-master.ts
packages/textlint/src/parallel/lint-worker.ts
tsconfig.base.json
website/package.json
yarn.lock

[Node v12.11.0](https://nodejs.org/en/blog/release/v12.11.0/) make [worker_threads](https://nodejs.org/api/worker_threads.html) stable.
We want to support parallel linting.
`textlint --parallel`  lint files in parallelly.
Refers to https://github.com/eslint/eslint/commit/284dd3555a795e7a37b75a452982a32a4c336d28

feat(textlint): support --parallel as experimental

---

docs/CONTRIBUTING.md
examples/use-as-ts-module/package.json
package.json
packages/@textlint/ast-node-types/package.json
packages/@textlint/ast-node-types/test/TextLintASTNodeTypes-test.ts
packages/@textlint/ast-tester/package.json
packages/@textlint/ast-traverse/package.json
packages/@textlint/feature-flag/package.json
packages/@textlint/fixer-formatter/package.json
packages/@textlint/kernel/package.json
packages/@textlint/linter-formatter/package.json
packages/@textlint/markdown-to-ast/package.json
packages/@textlint/module-interop/package.json
packages/@textlint/text-to-ast/package.json
packages/@textlint/textlint-plugin-markdown/package.json
packages/@textlint/textlint-plugin-text/package.json
packages/@textlint/types/package.json
packages/@textlint/utils/package.json
packages/gulp-textlint/package.json
packages/textlint-tester/package.json
packages/textlint/package.json
test/integration-test/package.json
yarn.lock

doc(CONTRIBUTING): add release flow

---

packages/@textlint/types/README.md

Add a note about duplicated issue.

docs(textlint/types): Add FAQ

---

docs/rule.md

docs(rule): add --typescript flag

---

docs/configuring.md
packages/textlint/src/config/config-loader.ts

Closes https://github.com/textlint/textlint/issues/643

Add configuration support for "textlint" field in package.json

---

docs/configuring.md
docs/use-as-modules.md
examples/config-in-package-json/CHANGELOG.md
examples/config-in-package-json/README.md
examples/config-in-package-json/package.json
packages/textlint/package.json
packages/textlint/src/config/config-loader.ts
packages/textlint/src/config/config.ts
packages/textlint/src/config/plugin-loader.ts
packages/textlint/test/config-initializer/config-initializer-test.ts
packages/textlint/test/config-loader/config-loader-test.ts
packages/textlint/test/config/config-as-example-test.js
packages/textlint/test/config/config-fixtures/package-json/expect.json
packages/textlint/test/config/config-fixtures/package-json/modules/textlint-filter-rule-example.js
packages/textlint/test/config/config-fixtures/package-json/modules/textlint-rule-preset-foo/index.js
packages/textlint/test/config/config-fixtures/package-json/modules/textlint-rule-preset-foo/package.json
packages/textlint/test/config/config-fixtures/package-json/modules/textlint-rule-preset-foo/rules/textlint-rule-a.js
packages/textlint/test/config/config-fixtures/package-json/modules/textlint-rule-preset-foo/rules/textlint-rule-b.js
packages/textlint/test/config/config-fixtures/package-json/package.json
yarn.lock

Add tests and example/config-in-package-json for #644

test(textlint): add text for package.json's "textlint"

---

packages/@textlint/linter-formatter/package.json

fix(linter-formatter): add missing dependencies

---

packages/@textlint/kernel/package.json
packages/@textlint/kernel/src/task/promise-event-emitter.ts
packages/@textlint/kernel/src/task/textlint-core-task.ts
packages/textlint/package.json
packages/textlint/src/cli.ts
packages/textlint/src/config/config-initializer.ts
packages/textlint/src/engine/execute-file-backer-manager.ts
packages/textlint/src/fixer/textlint-fixer.ts
packages/textlint/src/util/fs-promise.ts

refactor(textlint/kernel): use promise instead of bluebird

---

docs/CONTRIBUTING.md

- Script modified by 2d2b8916bcd992d4c7fbe10439a30b891178e067

docs(CONTRIBUTING): fix the website script to the latest version

---

.github/workflows/ci.yml

It is related with ?
```
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

CI: remove yarn installation

---

packages/@textlint/markdown-to-ast/src/index.ts
packages/@textlint/markdown-to-ast/test/markdown-parser-test.ts

refactor(markdown-to-ast): Convert tests to TypeScript

---

tsconfig.base.json

Reduce transpiled code.
fix https://github.com/textlint/textlint/issues/774

feat: base target is ES2015

---

packages/@textlint/ast-tester/package.json
packages/@textlint/ast-tester/src/index.ts
packages/@textlint/ast-tester/test/fixtures/invalid-ast.json
packages/@textlint/ast-tester/test/textlint-ast-tester-test.ts
packages/@textlint/kernel/package.json
packages/@textlint/kernel/src/fixer/fixer-processor.ts
packages/@textlint/kernel/src/textlint-kernel.ts
packages/@textlint/kernel/src/util/isPluginParsedObject.ts
packages/@textlint/kernel/test/kernel-plugin-test.ts
packages/@textlint/kernel/tsconfig.json

- kernel does not use ast-tester. Instead of it, detect the pluginParsedObject
- add tests for #649 when --fix mode
- mitigate the AST check and it improve perf

feat(ast-tester): improve error message

---

docs/plugin.md
packages/@textlint/kernel/package.json
packages/@textlint/kernel/src/textlint-kernel.ts
packages/@textlint/kernel/test/kernel-plugin-test.ts
packages/@textlint/kernel/tsconfig.json
packages/textlint-scripts/.eslintignore

feat(kernel): add runtime AST check if running in textlint-tester

---

packages/@textlint/feature-flag/package.json
packages/@textlint/feature-flag/src/index.ts
packages/@textlint/kernel/package.json
packages/textlint/package.json
packages/textlint/src/engine/processor-map.ts
packages/textlint/src/engine/rule-map.ts
yarn.lock

Fixes #792
Hi @azu, how does this look?
Let me know if this needs any changes.
Thanks

Use native map instead of map-like

---

README.md

Hi👋
I have developed a plugin for org-mode support!
[textlint-plugin-org](https://github.com/kijimaD/textlint-plugin-org "textlint-plugin-org")

Add textlint-plugin-org link

---

.github/workflows/ci.yml

CI: update permissions

---

website/siteConfig.js

from: https://textlint.github.io/users.html
Would you like to add 校正さん to user list?
校正さん is a note application with proofreading.
Textlint is used on browser.
detail: https://kohsei-san.b-hood.site/lp/

Add 校正さん to user list

---

packages/@textlint/module-interop/README.md

docs: Update README.md

---

.github/workflows/ci.yml
package.json
packages/@textlint/ast-node-types/package.json
packages/@textlint/ast-tester/package.json
packages/@textlint/ast-traverse/package.json
packages/@textlint/feature-flag/package.json
packages/@textlint/fixer-formatter/package.json
packages/@textlint/kernel/package.json
packages/@textlint/linter-formatter/package.json
packages/@textlint/markdown-to-ast/package.json
packages/@textlint/module-interop/package.json
packages/@textlint/text-to-ast/package.json
packages/@textlint/textlint-plugin-markdown/package.json
packages/@textlint/textlint-plugin-text/package.json
packages/@textlint/types/package.json
packages/@textlint/utils/package.json
packages/textlint-tester/package.json
packages/textlint/package.json

- Enable Cache
- https://github.com/actions/setup-node
- remove duplicated build task

CI: enable cache

---

packages/@textlint/kernel/src/context/TextlintRuleErrorImpl.ts
packages/@textlint/kernel/test/context/TextlintRuleError-test.ts

fix(textlint/kernel): improve RuleError error handlong

---

README.md

resolve https://github.com/textlint/textlint/issues/885

docs(readme): delete --global in readme Closes #885

---

README.md

docs: use npx

---

website/siteConfig.js

「校正さん」アプリが復活しました 2022/10/10
https://helpfeel.com/hata6502/--63433237c773a9001d16f4d0

Update link to 「校正さん」

---

packages/@textlint/types/src/index.ts

Expose TextlintPluginPreProcessResult/TextlintPluginPostProcessResult type

---

.github/workflows/ci.yml
.github/workflows/website.yml
docs/CONTRIBUTING.md
nx.json
package.json
packages/@textlint/markdown-to-ast/tools/create-fixtures.js
packages/@textlint/markdown-to-ast/tools/update-fixtures.js
yarn.lock

Update Lerna.
- what is alternative for [--ignore](https://lerna.js.org/docs/lerna6-obsolete-options#--ignore)?

feat(monorepo): upgrade to lerna@6 and use NX

---

packages/@textlint/kernel/src/fixer/fixer-processor.ts
packages/@textlint/kernel/src/linter/linter-processor.ts

I think these should be `Unknown`.

chore(kernel): fix typo

---

packages/textlint/src/config/config-initializer.ts
packages/textlint/test/config-initializer/config-initializer-test.ts

Create `.textlintrc.json` instead of `.textlintrc`
fix #1012

fix(textlint): textlint --init create .textlintrc.json

---

tsconfig.base.json

Require ES2018 support env
- https://node.green/#ES2018

chore: Change "target" to "ES2018"

---

package.json
packages/textlint-scripts/example-ts/package.json
packages/textlint-scripts/example-ts/src/module.ts
packages/textlint-scripts/example-ts/test/index-test.ts
packages/textlint-scripts/example-ts/tsconfig.json
packages/textlint-scripts/example/package.json
packages/textlint-tester/tsconfig.json
tsconfig.json
yarn.lock

refactor: add textlint-script/example* to workspaces

---

package-lock.json
packages/@textlint/config-loader/package.json
packages/@textlint/kernel/package.json
packages/@textlint/kernel/src/descriptor/TextlintFilterRuleDescriptor.ts
packages/@textlint/kernel/src/descriptor/TextlintLintableRuleDescriptor.ts
packages/@textlint/kernel/src/descriptor/TextlintPluginDescriptor.ts
packages/@textlint/kernel/test/descriptor/TextlintPluginDescritors-test.ts
packages/@textlint/source-code-fixer/package.json
packages/textlint/package.json

refactor(kernel): use fast-equals instead of deep-equal

---

package-lock.json
packages/textlint/package.json

https://bundlephobia.com/package/textlint@13.0.3
It will remove esprima from textlint's deps.

chore(deps): update to rc-config-loader@4

---

docs/getting-started.md
packages/textlint/src/config/config-initializer.ts
packages/textlint/test/config-initializer/config-initializer-test.ts
packages/textlint/test/config-initializer/fixtures/package.json

feat(textlint): support `plugins` for `--init` option

---

packages/textlint-tester/README.md
packages/textlint-tester/src/test-util.ts
packages/textlint-tester/src/textlint-tester.ts
packages/textlint-tester/test/textlint-tester-error-format.ts
packages/textlint-tester/test/textlint-tester-invalid-test.ts

This PR attempts to add the  `description` option to textlint-tester.
closes: https://github.com/textlint/textlint/issues/1005

feat(textlint-tester): add description field

---

docs/configuring.md
docs/faq/failed-to-load-textlints-module.md
packages/@textlint/config-loader/test/snapshots/preset/input.json
packages/@textlint/config-loader/test/snapshots/preset/output.json
packages/@textlint/config-loader/test/snapshots/textlintv12-invalid-scoped-rule-specifier/input.json
packages/@textlint/config-loader/test/snapshots/textlintv12-invalid-scoped-rule-specifier/output.json

docs: improve failed-to-load-textlints-module.md

---

tsconfig.json

chore: update project references

---

.github/workflows/release-canary.yml
package-lock.json

Support Canary Release for testing.

CI: add canary-release workflow

---

packages/@textlint/ast-node-types/src/NodeType.ts

add TxtCommentNode to StaticPhrasingContent

---

packages/@textlint/kernel/src/context/TextlintRuleSeverityLevelKeys.ts
packages/@textlint/kernel/test/textlint-kernel-test.ts
packages/@textlint/types/src/Rule/TextlintRuleOptions.ts
packages/@textlint/types/src/Rule/TextlintRuleSeverityLevelKey.ts
packages/@textlint/types/src/index.ts

fix TextlintRuleOptions severity Type
Closes #1367

fix(textlint): fix severity type

---

package-lock.json
packages/textlint-scripts/examples/example-dynamic-import/package.json
packages/textlint-scripts/examples/example-ts/package.json
packages/textlint-scripts/examples/example/README.md
packages/textlint-scripts/examples/example/package.json
packages/textlint-scripts/package.json
packages/textlint-scripts/scripts/init.js
packages/textlint-scripts/test/test-example.js

- Update to https://github.com/azu/pkg-to-readme/releases/tag/v3.0.0
- Add `--yes` flag. e.g. `textlint-scripts init --yes`
- This is for testing the new flag
- Add test for `textlint-scripts init`

feat(textlint-scripts): update to pkg-to-readme@3 and `textlint-scripts init --yes`

---

package-lock.json
packages/@textlint/config-loader/package.json
packages/@textlint/config-loader/src/import.ts
packages/@textlint/config-loader/src/index.ts
packages/@textlint/config-loader/src/is.ts
packages/@textlint/config-loader/src/loader.ts
packages/@textlint/config-loader/src/textlint-module-resolver.ts
packages/@textlint/config-loader/tsconfig.json
packages/@textlint/fixer-formatter/package.json
packages/@textlint/fixer-formatter/src/index.ts
packages/@textlint/fixer-formatter/tsconfig.json
packages/@textlint/legacy-textlint-core/tsconfig.json
packages/@textlint/linter-formatter/package.json
packages/@textlint/linter-formatter/src/index.ts
packages/@textlint/linter-formatter/tsconfig.json
packages/@textlint/resolver/.mocharc.json
packages/@textlint/resolver/LICENSE
packages/@textlint/resolver/README.md
packages/@textlint/resolver/package.json
packages/@textlint/resolver/src/index.ts
packages/@textlint/resolver/test/index.test.ts
packages/@textlint/resolver/tsconfig.json
packages/@textlint/resolver/tsconfig.module.json
packages/textlint/package.json
packages/textlint/src/DEPRECATED/engine/textlint-module-resolver.ts
packages/textlint/src/engine/rule-loader.ts
packages/textlint/tsconfig.json
tsconfig.json

- Add `@textlint/resolver`
- Remove deprecated `try-resolve` package
fix #1406

feat(resolver): use @textlint/resolver instead of try-resolve

---

package-lock.json

chore(deps): update axios

---

package-lock.json
package.json
packages/@textlint/legacy-textlint-core/src/index.ts
packages/textlint-tester/test/textlint-tester-error-format.ts

Add `fixFile` API to @textlint/legacy-textlint-core because original　`TextlintCore` has `fixFile` API.

feat(@textlint/legacy-textlint-core): add `fixFile` API

---

docs/cli.md
packages/textlint/bin/textlint.js

Fixed some documents since renamed option `--dryRun` remained.

Replace `--dryRun` with `--dry-run`

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/create-release-pr.yml
.github/workflows/release-canary.yml
.github/workflows/release.yml
.github/workflows/website.yml

Pin all actions's version.
```
pinact run
pinact run -u
```
https://github.com/suzuki-shunsuke/pinact

CI: pin actions's version

---

website/siteConfig.js

fix(website): fix `CNAME` config

---

website/siteConfig.js

chore(website): use new docsearch api key

---

packages/@textlint/kernel/src/task/linter-task.ts
packages/@textlint/text-to-ast/test/compliance-test.ts
packages/textlint/src/DEPRECATED/engine/textlint-engine-core.ts
packages/textlint/src/DEPRECATED/textlint-core.ts

refactor unnecessarily renamed & import multiple times

refactor: unnecessarily renamed & import multiple times

---

package-lock.json
website/package.json

chore: remove unused clsx dependency

---

README.md
docs/README.md
docs/integrations.md
docs/mcp.md

Add documents for #1498 
cc @chick-p

docs: Add --mcp usage

---

website/sidebars.json

docs: add mcp

---

packages/@textlint/config-loader/src/textlint-package-name-util.ts
packages/@textlint/utils/src/KeyPath/KeyPathUtil.ts

use for..of instead of traditional for loop for better readability

refactor: use for..of instead of traditional for loop

---

packages/@textlint/config-loader/test/index.test.ts
packages/@textlint/kernel/test/helper/AsyncPlugin.ts
packages/@textlint/kernel/test/helper/BinaryPlugin.ts
packages/@textlint/kernel/test/textlint-kernel-snapshots-test.ts
packages/textlint/test/cli/fixtures/rules/async-rule.js

remove unused import & imported multiple times

refactor: remove unused import & imported multiple times

---

.github/workflows/merge-gatekeeper.yml

add https://github.com/upsidr/merge-gatekeeper

CI: add Merge Gatekeeper workflow for pull requests

---

packages/@textlint/resolver/package.json
packages/textlint/package.json

chore: fix clean script

---

package.json
pnpm-lock.yaml

update globals from v15 to v16
- <https://github.com/sindresorhus/globals/releases>

chore: update globals from v15 to v16

---

docs/migration-to-v15.md
docs/rule.md
examples/perf/md/creation.md
examples/perf/md/delete.md
examples/perf/md/properties.md
packages/textlint-tester/README.md
packages/textlint-tester/test/textlint-tester-invalid-testcofig.test.ts
packages/textlint/src/engine/execute-file-backers/README.md
packages/textlint/test/config-initializer/config-initializer.test.ts
packages/textlint/test/pluguins/PluginOption.test.ts
packages/textlint/test/rule-context/rule-context.test.ts
website/blog/2018-05-22-new-website.md
website/blog/2018-07-22-textlint-11.md
website/blog/2024-02-03-textlint-14.md

chore: fix typos

---

packages/@textlint/config-loader/test/modules_fixtures/textlint-rule-preset-abc-with-severity/index.js
packages/@textlint/config-loader/test/snapshots/preset-severity-preservation/input.json
packages/@textlint/config-loader/test/snapshots/preset-severity-preservation/output.json

add test case for config loader

test(config-loader): add user config is `true` case

---

packages/textlint/src/mcp/server.ts
packages/textlint/test/mcp/fixtures/.textlintrc.json
packages/textlint/test/mcp/fixtures/invalid.md
packages/textlint/test/mcp/server.test.ts

fix(mcp): allow additional properties in TextlintMessage schema

---

packages/textlint-tester/src/textlint-tester.ts
packages/textlint-tester/test/textlint-tester.test.ts

Closes https://github.com/textlint/textlint/issues/1697.

fix(textlint-tester): support empty string test cases

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/create-release-pr.yml
.github/workflows/release-canary.yml
.github/workflows/release.yml
.github/workflows/website-preview.yml
.github/workflows/website.yml

CI: fix actions

---

packages/@textlint/kernel/src/descriptor/TextlintRuleDescriptors.ts
packages/@textlint/linter-formatter/test/formatters/checkstyle.test.ts
packages/@textlint/linter-formatter/test/formatters/compact.test.ts
packages/@textlint/linter-formatter/test/formatters/jslint-xml.test.ts
packages/@textlint/linter-formatter/test/formatters/json.test.ts
packages/@textlint/linter-formatter/test/formatters/tap.test.ts
packages/@textlint/linter-formatter/test/formatters/unix.test.ts

refactor: remove unnecessary assertion

---

docs/example/rules/example-rule.js
examples/perf/perf.js
examples/perf/run.js
examples/rulesdir/rules/no-todo.js
packages/@textlint/config-loader/src/is.ts
packages/@textlint/config-loader/src/loader.ts
packages/@textlint/config-loader/test/index.test.ts
packages/@textlint/kernel/test/textlint-kernel.test.ts
packages/@textlint/linter-formatter/src/formatters/pretty-error.ts
packages/@textlint/linter-formatter/test/formatters/junit.test.ts
packages/@textlint/linter-formatter/test/formatters/pretty-error.test.ts
packages/@textlint/linter-formatter/test/test-helper.ts
packages/@textlint/markdown-to-ast/test/markdown-parser.test.ts
packages/@textlint/textlint-plugin-markdown/src/MarkdownProcessor.ts
packages/@textlint/textlint-plugin-text/src/TextProcessor.ts
packages/textlint/test/cli-snapshot-test/cli-snapshots.test.ts
packages/textlint/test/cli/cli-exit-status-faq.test.ts
packages/textlint/test/cli/cli-preset-severity.test.ts
packages/textlint/test/cli/cli.test.ts
packages/textlint/test/config-initializer/config-initializer.test.ts
website/docusaurus.config.js

refactor: format code
