lib/config/config-loader.js, lib/textlint-engine.js
use `tryResolve` instead of `tryResolve.relative`
`tryResolve.relative` don't load global installed module.
=> fix(config): support for requiring global installed rule

lib/textlint-engine.js, lib/textlint.js, test/textlint-engine-test.js
Split out load rule with `ruleName` into `TextLintEngine#loadRule`.
This change allow to load rule with ruleName on external project like atom plugin.
#19
=> Add TextLintEngine#loadRule

lib/config/config.js, lib/textlint-engine.js, package.json, test/textlint-engine-test.js
- `TextLintEngine.prototype.executeOnFiles`
- `TextLintEngine.prototype.executeOnText`
のタイミングで都度`setupRules`を実行していますが、`config`が渡されるタイミング（現状`TextLintEngine`のコンストラクタのみ）の方がパフォーマンス的にも良さそうです
=> accept both ruleName and rulePath

lib/_typing/textlint.d.ts, lib/config/config.js, lib/rule/rule-context.js, lib/textlint-engine.js, lib/textlint.js, test/textlint-test.js
RuleContext has `config` that is textlint's config object.
It mean that allow to get config from each rules.
This resolve https://github.com/azu/textlint/issues/24
=> feat(context): add config to RuleContext

docs/txtnode.d.ts, docs/txtnode.md, src/textlint-core.js
Add docs about location indexed.
```
interface Position {
line: number; // start with 1
column: number;// start with 0
// This is for compatibility with JavaScript AST.
// https://gist.github.com/azu/8866b2cb9b7a933e01fe
}
```
- `line` - 1-indexed
- `column` - 0-indexed
=> docs(txtnode): why line of location start with 1?

src/textlint-core.js, test/textlint-core-test.js
Currently, textlint throws an exception when it checks an empty text(file).
* stacktrace
```
AssertionError: false == true
at TextlintCore._lintByProcessor (/Users/koba04/github/textlint/lib/textlint-core.js:133:30)
at TextlintCore.lintFile (/Users/koba04/github/textlint/lib/textlint-core.js:203:25)
at /Users/koba04/github/textlint/lib/textlint-engine.js:196:33
at Array.map (native)
at TextLintEngine.executeOnFiles (/Users/koba04/github/textlint/lib/textlint-engine.js:195:39)
at Object.execute (/Users/koba04/github/textlint/lib/cli.js:75:70)
at Object.<anonymous> (/Users/koba04/github/textlint/bin/textlint.js:14:20)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
```
This PR is for textlint allows an empty …
=> allow an empty text with lint

src/config/config.js, src/textlint-core.js, src/textlint-engine.js, test/textlint-engine-test.js
no use textlint.js(singleton) in textlint-engine.js
I think this change make linting phase more scalable.
=> refactor(engine): directly use textlint-core

docs/formatter.md, src/rule/rule-context-agent.js, src/rule/rule-context.js, test/rule-context-test.js, typing/textlint.d.ts
`context.report(node, error|data)` can also report any data.
It is useful for usage other than linting. 
```js
export default function (context) {
return {
[context.Syntax.Str](node){
context.report(node, {
message : "message",
customKey: "value"
);
}
}
}
```
=> feat(rule-context): `context.report` can also report any data 

src/config/config.js, src/textlint-engine.js, test/config-test.js, test/textlint-engine-test.js
- `new Config` => not load ConfigFile, init Config
- `Config.initWithAutoLoading` => load ConfigFile and init Config
=> refactor(config): split up config into Constructor and loading config

.jscsrc, src/rule/compute-location.js, src/rule/rule-context-agent.js, test/rule-context-test.js
When report with padding {line, column}, `message.column` should be `0 + padding.column`.
In other word, padding line > 0 and `message.column` start with 0.
=> fix(rule-context): correct padding column number

README.md, src/options.js
See: https://github.com/eslint/eslint/commit/741d0c1f83a877c51ce71773bb2c4041a808a1f2
The second commit update CLI doc in README with current help output.
=> Negate help message of --no-color option

docs/.textlintrc, docs/configuring.md, docs/formatter.md, docs/plugin.md, docs/rule.md, docs/txtnode.md, package.json
lint textlint's docs by it-self.
- [azu/textlint-rule-rousseau: textlint rule check english sentence using rousseau](https://github.com/azu/textlint-rule-rousseau)
- [azu/textlint-rule-unexpanded-acronym: textlint rule that check unexpanded acronym.](https://github.com/azu/textlint-rule-unexpanded-acronym)
We want to rules for english text.
(@azu is not native speaker...)
=> fix(docs): lint docs by textlint

README.md, src/cli.js, src/options.js, src/textlint-engine.js, test/textlint-engine-test.js
Currently, We can't specify a file type to process STDIN as.
To fix #117 and we will treat STDIN's content as markdown file.
cat ./README.md | textlint --stdin --stdin-filename README.md
However, some formatter still un-available on STDIN.
Because `pretty-error` formatter read actual file.
We will improve that at next time.
#117
=> feat(cli): add `--stdin-filename` option

README.md
As of https://github.com/SublimeLinter/package_control_channel/commit/c0c071fe96437ec67b1f437186034f1d25459b64 textlint is now available for SublimeText.
=> Add sublime plugin information

src/engine/textlint-engine-core.js, test/cli-test.js, test/fixtures/cli/pass.html, test/fixtures/cli/todo.html, test/textlint-engine-test.js
When load a plugin, then add available extensions like .html" to core.
But, `engine.availableExtensions` always is empty at  textlint v6.0.3.
fix #180
=> fix(plugin): fix 3rd party plugin is not working

package.json, src/config/config.js, src/config/plugin-loader.js, src/engine/textlint-engine-core.js, test/config-fixtures/has-a-processor-plugin/.textlintrc, test/config-fixtures/has-a-processor-plugin/expect.json, test/config-fixtures/has-a-processor-plugin/modules/textlint-plugin-pl-example/index.js, test/config-fixtures/has-a-processor-plugin/modules/textlint-plugin-pl-example/package.json, test/fixtures/engine/textlint-module-resolver/preset.js, test/fixtures/plugin-loader/textlint-plugin-has-not-processor.js, test/fixtures/plugin-loader/textlint-plugin-has-not-rulesconfig.js, test/fixtures/plugin-loader/textlint-plugin-has-processor-4-extensions.js, test/fixtures/plugin-loader/textlint-plugin-has-processor.js, test/fixtures/plugin-loader/textlint-plugin-has-rulesconfig.js, test/plugin-loader-test.js, test/pluguins/HTMLProcessor-test.js
- it is need to keep backward compatibiliy
- it will remove next major update?
=> refactor(plugin): move availableExtensions to Config

src/textlint-core.js, test/rule-context/fixtures/rules/throw-error-in-rule.js, test/rule-context/rule-context-test.js
When throw error  in the rule.
```js
module.exports = function (context) {
var exports = {};
exports[context.Syntax.Str + ":exit"] = function () {
throw new Error("Error in rule");
};
return exports;
};
```
Before:
Error in rule
After:
Error in rule at ~/textlint/textlint/test/rule-context/fixtures/test.md
Fix #165
=> feat(core): add fileName to trailing of error message

docs/rule.md, src/core/rule-context.js, src/shared/message-filter.js, src/task/textlint-core-task.js, test/message-filter/message-filter-test.js, test/rule-context/rule-context-test.js
When the `ruleId` of option object is matched ruleId of error message, filter only the message,
Default is filter all message in the ignoring range.
https://github.com/textlint/textlint-rule-ignore-comment
```
this is wrong
```
Disable specific rule on the fly.
=> feat(ignore): add `{ ruleId }` option object to `shouldIgnore`

package.json, src/config/config-initializer.js, test/config-initializer/config-initializer-test.js, test/config-initializer/fixtures/package.json
- fill "rules" with installed rule packages
- support "filters" field
When package.json has `textlint-rule-alex`
```json
"devDependencies": {
"textlint-rule-alex": "^1.0.1"
},
```
Then `textlint --init` should create follwoing `.textlintrc`
```json
{
"rules": {
"alex": true
}
}
```
close #129
=> feat(cli): --init fill "rules" with installed rule packages

docs/rule.md
Recommended to use setup scripts.
- [textlint/create-textlint-rule: Create textlint rule project with no configuration.](https://github.com/textlint/create-textlint-rule)
- [textlint/textlint-scripts: textlint npm-run-scripts CLI help to create textlint rule.](https://github.com/textlint/textlint-scripts)
=> docs(rule): use `create-textlint-rule` and `textlint-scripts`

packages/textlint/package.json, packages/textlint/src/config/config-loader.js, packages/textlint/test/config/config-as-example-test.js, packages/textlint/test/config/config-fixtures/yml-ext/.textlintrc.yml, packages/textlint/test/config/config-fixtures/yml-ext/expect.json, packages/textlint/test/config/config-fixtures/yml-ext/modules/textlint-rule-a.js, packages/textlint/test/config/config-fixtures/yml-ext/modules/textlint-rule-b.js, packages/textlint/test/config/config-fixtures/yml-ext/modules/textlint-rule-c.js
This is alternative PR #258 for #39 
- [azu/rc-config-loader: Load config from .{product}rc.{json,yml,js} file](https://github.com/azu/rc-config-loader "azu/rc-config-loader: Load config from .{product}rc.{json,yml,js} file")
fix #39
=> fix(config): use rc-config-loader insteadof rc-loader

packages/textlint/src/config/config.js, packages/textlint/src/messages/filter-severity-process.js, packages/textlint/src/textlint-core.js, packages/textlint/test/cli/cli-test.js, packages/textlint/test/cli/fixtures/.textlintrc.quiet
`--quiet` option is listed on the help, but it seems not working now.
This PR includes 3 changes:
- Add `quiet` property to Config
- Add `packages/textlint/src/messages/filter-severity-process.js` 
- Add a test for CLI `--quiet` option
=> feat(cli): Support quiet mode

packages/textlint/src/fixer/formatters/stylish.js, packages/textlint/src/textlint-core.js
#273
stylish formatter is broken when passing following results:
```js
[ { messages : []. filePath }]
```
=> fix(fixer): fix thrown error when empty result.

packages/textlint/package.json, packages/textlint/src/util/find-util.js, packages/textlint/yarn.lock
fix #285 
test code : re-use on #286 
```
// MIT © 2017 azu
"use strict";
const assert = require("assert");
const path = require("path");
const webpack = require("webpack");
const os = require("os");
const sh = require("shelljs");
const libDir = path.join(__dirname, "..", "..", "lib");
const entry = path.join(libDir, "index.js");
const outputDir = `${os.tmpdir()}/textlint/tests/browser/`;
sh.mkdir("-p", outputDir);
webpack({
context: libDir,
entry: entry,
output: {
path: outputDir,
filename: "bundle.js"
},
node: {
fs: "empty",
module: "empty"
},
devtool: false
}, (error, stat) => {
if (error) {
throw error;
}
console.log(stat.compilation.errors);
assert.equal(stat.compilation.errors.length, 0);
});
```
=> fix(textlint): remove shelljs dependencies

docs/plugin.md, packages/textlint-kernel/src/core/filter-rule-context.ts, packages/textlint-kernel/src/core/rule-context.ts, packages/textlint-kernel/src/task/textlint-core-task.ts, packages/textlint-kernel/src/textlint-kernel.ts, packages/textlint-kernel/test/helper/ExamplePlugin.ts, packages/textlint-kernel/test/textlint-kernel-test.ts, packages/textlint/src/config/config.js, packages/textlint/src/config/plugin-loader.js, packages/textlint/src/core/plugin-creator-set.js, packages/textlint/src/engine/textlint-engine-core.js, packages/textlint/src/textlint-core.js, packages/textlint/test/config/config-fixtures/plugin-config/.textlintrc, packages/textlint/test/config/config-fixtures/plugin-config/expect.json, packages/textlint/test/config/config-fixtures/plugin-config/modules/textlint-plugin-pl-example/index.js, packages/textlint/test/config/config-fixtures/plugin-config/modules/textlint-plugin-pl-example/package.json, packages/textlint/test/plugin-loader/plugin-loader-test.js, packages/textlint/test/pluguins/PluginOption-test.js, packages/textlint/test/pluguins/fixtures/example-plugin.js
- `kernel` support plugin option via `{ pluginId, plugin, options }`.
- `textlint` support plugin option via `TextlintCore#setupPlugins(plugins, pluginsConfig)`
You can pass a options to your plugin from `.textlintrc`.
```
{
"plugins": {
pluginName: processorOption
}
}
```
You can receive the `processorOption` via constructor arguments.
```js
export default class YourProcessor {
constructor(options) {
this.options = options; // <= processorOption!
}
// ...
}
```
fix #296
=> feat(kernel): support plugin options

packages/textlint/src/engine/rule-loader.js
=> fix(textlint): use `path.basename` instead of slice

.travis.yml
`yarn run prepare` is called twice.
=> chore(travis): remove duplicated "prepare" scripts

packages/textlint/bin/textlint.js
error.code is a string, not a number.
https://nodejs.org/api/errors.html#errors_error_code
=> fix(textlint): don't use error.code when catch error

packages/textlint-tester/README.md, packages/textlint-tester/src/test-util.js, packages/textlint-tester/test/textlint-tester-test.js
Allow to write following `index` based testing.
```js
// index
{
text: "- [ ] string",
errors: [
{
message: "Found TODO: '- [ ] string'",
index: 2
}
]
},
```
=> feat(textlint-tester): support "index" expected param

docs/configuring.md, docs/filter-rule.md, docs/plugin.md, packages/textlint/src/engine/textlint-module-resolver.js, packages/textlint/test/textlint-module-resolver/fixtures/@textlint/textlint-rule-scoped-rule/index.js, packages/textlint/test/textlint-module-resolver/fixtures/@textlint/textlint-rule-scoped-rule/package.json, packages/textlint/test/textlint-module-resolver/textlint-module-resolver-test.js
`@scope/name` -> `@scope/textlint-rule-name`.
fix #271
=> feat(textlint): support shortcut scoped package name

packages/textlint-kernel/package.json, packages/textlint/src/engine/textlint-module-resolver.js, packages/textlint/src/util/config-util.js, packages/textlint/test/config/config-fixtures/preset-short-scoped-module/.textlintrc, packages/textlint/test/config/config-fixtures/preset-short-scoped-module/expect.js, packages/textlint/test/config/config-fixtures/preset-short-scoped-module/modules/@textlint/textlint-rule-preset-foo/index.js, packages/textlint/test/config/config-fixtures/preset-short-scoped-module/modules/@textlint/textlint-rule-preset-foo/package.json, packages/textlint/test/config/config-fixtures/preset-short-scoped-module/modules/@textlint/textlint-rule-preset-foo/rules/textlint-rule-a.js, packages/textlint/test/textlint-module-resolver/fixtures/@textlint/textlint-rule-preset-example/index.js, packages/textlint/test/textlint-module-resolver/fixtures/@textlint/textlint-rule-preset-example/package.json, packages/textlint/test/textlint-module-resolver/fixtures/@textlint/textlint-rule-preset-example/rules/textlint-rule-a.js, packages/textlint/test/textlint-module-resolver/fixtures/@textlint/textlint-rule-preset-example/rules/textlint-rule-b.js, packages/textlint/test/textlint-module-resolver/textlint-module-resolver-test.js
Follow up #326 
fix #327 
Work following config.
```
{
"filters": {
"comments": true
},
"rules": {
"@textlint-rule/preset-google": true
}
```
=> fix(textlint): support scoped preset module 

.github/CONTRIBUTING.md
- we use not npm but yarn
- at first, run `yarn install`
- next, run `tarn run bootstrap` to bootstrap child packages
Closes #339
=> docs(CONTRIBUTING): add installation guide

docs/use-as-modules.md, packages/textlint/src/index.ts
This PR closes #337 
- Fixed `FIXME` comment because test passed even if remove constant types.
- Update Use as module documentation
=>  refactor(textlint): export as ES module

docs/rule.md
Add [@textlint/get-config-base-dir](https://github.com/textlint/get-config-base-dir "@textlint/get-config-base-dir") as polyfill.
Related issue: https://github.com/textlint/textlint-filter-rule-whitelist/issues/4
=> docs(rule): Update RuleContext API

.github/CONTRIBUTING.md
For first time contributors, following changes should be added in order
to finish integration test without error. Will fix textlint/textlint#377.
- Add `--recursive` to `git clone` on [Install](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md#install) section.
- Add `--init` to `git submodule update` on [Integration Test](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md#integration-test) section.
=> docs(CONTRIBUTING): Add option to git clone/submodule

docs/txtnode.md, packages/@textlint/ast-node-types/src/TextLintASTNodeTypes.ts, yarn.lock
- `TxtNode` allow to set optional property
- Update txtnode.md
- Remove `TxtRootNode` from `@textlint/ast-node-types`
`@textlint/ast-node-types`'s scope is Abstract Syntax Tree.
It is inspiered by [unist](https://github.com/syntax-tree/unist "unist").
`@textlint/ast-node-types` does not include detailed Node interface like `StrNode`.
=> fix(ast-node-types): Make TxtNode non-weak type

lerna.json, test/integration-test/package.json, yarn.lock
Currently, CI failed by https://github.com/textlint/textlint/pull/384#issuecomment-352010845
Add `integration-test` to lerna.json again and refer latest `textlint@10.0.0-next.0`.
=> fix(integration-test): Add integration-test to lerna.json

packages/@textlint/kernel/package.json, packages/@textlint/kernel/tools/update-json-schema.js, packages/textlint/package.json, yarn.lock
This PR closes #362 and closes #368.
- Remove `typescript-json-schema` from kernel.
- And remove `tools/update-json-schema.js` (It depends on `typescript-json-schema` but not used)
- Remove `resolve` from textlint.
=> Remove unused packages

.github/CONTRIBUTING.md
To prevent `Cannot find module '../lib/textlint/src/cli'` for first run. Closes #381.
=> docs(CONTRIBUTING): add instruction before lint

packages/textlint-tester/README.md, packages/textlint-tester/src/test-util.js, packages/textlint-tester/src/textlint-tester.js, packages/textlint-tester/test/fixtures/text/fixture-rule-add.md, packages/textlint-tester/test/fixtures/text/ng.md, packages/textlint-tester/test/fixtures/text/ok.md, packages/textlint-tester/test/textlint-tester-fixer-test.js, packages/textlint-tester/test/textlint-tester-invalid-test.js, packages/textlint-tester/test/textlint-tester-test.js
#390 https://github.com/textlint-rule/textlint-rule-no-dead-link/issues/94
Add `inputPath` option for valid and invalid option.
We will need to add `outputPath` support.
fix #390
=> feat(textlint-tester): support `inputPath` option

packages/textlint-tester/src/test-util.js, packages/textlint-tester/test/async-test.js
=> fix(textlint-tester): Correct output ${text}

packages/textlint-formatter/package.json
Correct mocha test glob pattern to run all tests. Closes #402.
=> fix(textlint-formatter): run all tests

packages/textlint-formatter/lib/formatters/jslint-xml.js, packages/textlint-formatter/test/formatters/jslint-xml.js
Modify test case as well. Closes #400.
Please note that commit 72136e3 (#407) reverts commit 1548585 (#403) and causes failed test in local.
```sh
cd packages/textlint-formatter
yarn run test # fail
yarn run test --no-color # success
```
=> refactor(textlint-formatter): remove reference to always empty string

packages/textlint-formatter/README.md, packages/textlint-formatter/src/cli.ts, packages/textlint-formatter/src/textlint-formatter.ts, packages/textlint-formatter/test/textlint-formatter-test.ts
Hi, could you review my pull request for for textlint-formatter?
References:
- [show available formatter in help · Issue #85 · textlint/textlint](https://github.com/textlint/textlint/issues/85)
- [formatter: Add `getFormatterList` function · Issue #399 · textlint/textlint](https://github.com/textlint/textlint/issues/399)
- [feat(textlint-fixer-formatter): add getFormatterList function by 0x6b · Pull Request #412 · textlint/textlint](https://github.com/textlint/textlint/pull/412)
=> feat(textlint-formatter): add getFormatterList function

README.md, packages/textlint/package.json, packages/textlint/src/options.ts, packages/textlint/test/cli/cli-test.js, packages/textlint/test/cli/fixtures/help.txt
Hi, I implemented feature #85, choosing option 2 for its simplicity. Could you please review my implementation?
> ### Implementation Options
> 
> Which is better?
> 
> - `textlint -f -h` show formatter names?
>     - [generateHelpForOption(optionName)](https://github.com/gkz/optionator#generatehelpforoptionoptionname "generateHelpForOption(optionName)") and [longDescription](https://github.com/gkz/optionator#generatehelpforoptionoptionname "longDescription")
> - `textlint -h` show formatter names?
>     - simple
=> feat(textlint): show available formatter in help

.travis.yml, appveyor.yml, package.json, yarn.lock
> [yarn install --frozen-lockfile](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-frozen-lockfile "yarn install --frozen-lockfile")
> Don’t generate a yarn.lock lockfile and fail if an update is needed.
> [yarn check --integrity](https://yarnpkg.com/en/docs/cli/check "yarn check --integrity")
> Verifies that versions and hashed value of the package contents in the project’s package.json matches that of yarn’s lock file. This helps to verify that the package dependencies have not been altered.
fix #386
=> chore(yarn): add yarn-check scripts

packages/@textlint/ast-node-types/src/index.ts, packages/@textlint/kernel/src/core/filter-rule-context.ts, packages/@textlint/kernel/src/core/rule-context.ts
BREAKING CHANGE: TypeScript need to use it as enum
String enum has benefit
- Iterable for of
- Support Index signature
Details desription in japanese.
http://blog.yux3.net/entry/2017/12/05/102528
fix #422
=> chore(ast-node-types): Make ASTNodeTypes string enum

packages/textlint-fixer-formatter/src/index.ts, packages/textlint-fixer-formatter/test/textlint-fixer-formatter-test.ts, packages/textlint/src/options.ts
- Renamed `getFormatterList` to `getFixerFormatterList`
- make `getFormatterList()` function return type explicit
- Define `FixerFormatterDetail[]`
- `textlint-formatter` already support `FormatterDetail`
- textlint use the `FormatterDetail` and `FixerFormatterDetail`
=> refactor(textlint-fixer-formatter): make `getFormatterList()` return type explicit 

examples/perf/package.json
`textlint-example-perf` is not parts of test.
fix  #433
=> chore(perf): `yarn test` ignore `perf` test

docs/filter-rule.md, docs/formatter.md, docs/getting-started.md, docs/plugin.md, docs/rule-advanced.md, docs/rule.md, docs/txtnode.md, docs/use-as-modules.md
- [Advanced: Paragraph rule](https://github.com/textlint/textlint/blob/master/docs/rule-advanced.md)
- [Creating Rules](https://github.com/textlint/textlint/blob/master/docs/rule.md)
- [Filter rule](https://github.com/textlint/textlint/blob/master/docs/filter-rule.md)
- [Formatter](https://github.com/textlint/textlint/blob/master/docs/formatter.md)
- [Getting Started with textlint](https://github.com/textlint/textlint/blob/master/docs/getting-started.md)
- [Plugin](https://github.com/textlint/textlint/blob/master/docs/plugin.md)
- [TxtAST interface](https://github.com/textlint/textlint/blob/master/docs/txtnode.md)
- [Use as node modules](https://github.com/textlint/textlint/blob/master/docs/use-as-modules.md)
Closes #424. As discussed at #434, documentation could be improved but focused …
=> docs: fix multiple broken links and stale type interface

packages/textlint-formatter/test/textlint-formatter-test.ts, packages/textlint-formatter/test/ts-setup.js
- Add strict type check option to `ts-node` to make sure future
interface changes will be took into account while running test.
- Update test case for interface changes made at #430.
Closes #448.
=> test(textlint-formatter): check types while testing

docs/getting-started.md, package.json
This PR changes global install to local install in the installation of textlint. This PR is related to #191
=> docs(getting-started.md): use -D instead of -g

packages/@textlint/kernel/src/fixer/fixer-processor.ts
It makes processors to be able to use the filePath on a preProcess phase of fixing.
Before
--
`textlint --fix` is died if any processors use the filePath on preProcess phase.
After
--
`textlint --fix` works certainly even if any processors use the filePath on preProcess phase.
=> fix(kernel): pass the file path to preProcess() that is on FixerProcessor

packages/@textlint/ast-node-types/package.json, packages/@textlint/ast-node-types/test/mocha.opts, packages/@textlint/ast-node-types/test/ts-setup.js, packages/@textlint/ast-traverse/package.json, packages/@textlint/ast-traverse/test/mocha.opts, packages/@textlint/ast-traverse/test/ts-setup.js, packages/@textlint/fixer-formatter/package.json, packages/@textlint/fixer-formatter/test/mocha.opts, packages/@textlint/fixer-formatter/test/ts-setup.js, packages/@textlint/kernel/package.json, packages/@textlint/kernel/test/mocha.opts, packages/@textlint/kernel/test/ts-setup.js, packages/@textlint/linter-formatter/package.json, packages/@textlint/linter-formatter/test/mocha.opts, packages/@textlint/linter-formatter/test/ts-setup.js, packages/textlint-tester/package.json, packages/textlint-tester/test/mocha.opts, packages/textlint-tester/test/ts-setup.js, packages/textlint/package.json, packages/textlint/test/mocha.opts, packages/textlint/test/ts-setup.js, yarn.lock
In order to improve credibility and stability of tests, use
`ts-node-test-register` to:
- Load `tsconfig.json` from `test` directory
- Enforce `typeCheck` always
replacing `ts-setup.js` with `ts-node-test-register` in following
packages:
- `textlint-tester`
- `ast-node-types`
- `ast-traverse`
- `fixer-formatter`
- `kernel`
- `linter-formatter`
- `textlint`
https://www.npmjs.com/package/ts-node-test-register
Closes #451.
=> chore(test): use `ts-node-test-register` for TypeScript testing

packages/gulp-textlint/index.js, packages/gulp-textlint/package.json, yarn.lock
[`gulp-util`](https://github.com/gulpjs/gulp-util) has been deprecated.  
Though this is not critical for gulp-textlint, it is recommended to transition to individual modules.
For more information, see [this post](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5).
=> refactor(gulp-textlint): remove gulp-util

packages/@textlint/markdown-to-ast/package.json, packages/@textlint/markdown-to-ast/src/markdown-parser.js, packages/@textlint/markdown-to-ast/test/fixtures/frontmatter-empty.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/frontmatter-extra-dashes.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/frontmatter-initial-lines.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/frontmatter-normal.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/frontmatter-only.text/output.json, yarn.lock
Fix to parse yaml frontmatter as `YAML` node type.
It is compatibility for textlint@10.1.x <=
Fix #517 #515 
Refs #514
=> fix(markdown-to-ast): enable yaml frontmatter parse by default

README.md, docs/CONTRIBUTING.md, packages/textlint/package.json
=> Drop Node.js 4.x support from Docs

docs/plugin.md, docs/rule.md, packages/@textlint/kernel/package.json, packages/@textlint/kernel/src/descriptor/TextlintFilterRuleDescriptor.ts, packages/@textlint/kernel/src/descriptor/TextlintLintableRuleDescriptor.ts, packages/@textlint/kernel/src/descriptor/TextlintPluginDescriptor.ts, packages/@textlint/kernel/src/textlint-kernel-interface.ts, packages/@textlint/kernel/test/descriptor/TextlintRulesDescriptor-test.ts, packages/@textlint/kernel/test/helper/ExamplePlugin.ts, packages/@textlint/kernel/test/kernel-plugin-test.ts, packages/@textlint/kernel/test/textlint-kernel-test.ts, packages/@textlint/textlint-plugin-markdown/src/MarkdownProcessor.js, packages/@textlint/textlint-plugin-text/src/TextProcessor.js, packages/textlint-tester/src/textlint-tester.ts, packages/textlint-tester/test/textlint-tester-invalid-testcofig-test.ts, packages/textlint/src/engine/textlint-engine-core.ts, packages/textlint/src/textlint-core.ts, packages/textlint/src/util/object-to-kernel-format.ts, packages/textlint/test/engine/textfix-engine-test.ts, packages/textlint/test/engine/textlint-engine-test.ts, packages/textlint/test/object-to-kernel-format/fixtures/example-filter-rule.js, packages/textlint/test/object-to-kernel-format/fixtures/example-plugin.js, packages/textlint/test/object-to-kernel-format/fixtures/example-rule.js, packages/textlint/test/object-to-kernel-format/object-to-kernel-format-test.ts, packages/textlint/test/pluguins/PluginOption-test.js, packages/textlint/test/pluguins/fixtures/example-plugin.js
BREAKING CHANGE: Previously, textlint pass `true` to rule and plugin as default value of option.
This commit change the default value to `{}` (empty object).
For example, `very-nice-rule`'s option is `true`(enable the rule) in `.textlintrc`
```json
{
"rules": {
"very-nice-rule": true
}
}
```
**Before**
`very-nice-rule.js` rule get `true` as `options`.
```js
export default function(context, options) {
console.log(options); // true
}
```
**After**:
`very-nice-rule.js` rule get `{}` (emptry object) as `options`.
```js
export default function(context, options) {
console.log(options); // {}
}
```
fix https://github.com/textlint/textlint/issues/535
=> fix(kernel): make rule and plugin's option value {} by default

package.json
Thank you for [your quick response](https://github.com/textlint/textlint/issues/544#issuecomment-410427813).
I changed package.json. Now prettier uses escaped double quotes.
=> fix(prettier): use escaped double quotes instead of single quotes

README.md, docs/getting-started.md, docs/rule.md, packages/textlint-tester/src/textlint-tester.ts
Previously, text only test case on `valid` is always passed
```
tester.run("no-todo", noTodo, {
valid: [ "text" ]
})
```
=> fix(textlint-tester): fix text only valid test is always passed

.travis.yml, README.md, packages/@textlint/kernel/src/fixer/source-code-fixer.ts, packages/@textlint/kernel/test/source-code-fixer/source-code-fixer-test.js, packages/gulp-textlint/package.json, yarn.lock
Previously, the result is different with Node.js 10 and 11.
Because, V8 update to use stable sort.
https://v8.dev/blog/array-sort
The order to apply fix was different.
Related issues:
- https://github.com/eslint/eslint/issues/6124
- https://github.com/eslint/eslint/commit/aeb0337ac3b86a8a8cad169597770a7096b299b0
=> fix(kernel): fix applyFix order on Node.js 11

docs/rule-tips-after-all.md, docs/rule.md, docs/txtnode.md, packages/@textlint/ast-node-types/src/TypeofTxtNode.ts, packages/@textlint/ast-node-types/src/index.ts, packages/@textlint/ast-node-types/test/TextLintASTNodeTypes-test.ts, packages/@textlint/types/src/Rule/TextlintFilterRuleModule.ts, packages/@textlint/types/src/Rule/TextlintRuleModule.ts, packages/textlint-tester/test/async-test.ts, packages/textlint/test/textlint-core/async-rule-test.ts
Add `TypeofTxtNode` type function to `"@textlint/ast-node-types"`.
You can get Node type for Type name by `TypeofTxtNode` in TypeScript.
```ts
// In TypeScript
import { ASTNodeTypes } from "@textlint/ast-node-types";
const nodeType = TypeofTxtNode<ASTNodeTypes.Str>; // TxtTextNode
```
These types are defined in `@textlint/ast-node-types`.
| Type name                       | Node type     | Description                          |
| ------------------------------- | ------------- | ------------------------------------ |
| ASTNodeTypes.Document           | TxtParentNode | Root Node                            |
| ASTNodeTypes.DocumentExit       | TxtParentNode |                                      |
| ASTNodeTypes.Paragraph          | TxtParentNode | Paragraph Node                       |
| …
=> fix(@textlint/types): enhance `TextlintRuleReportHandler` typing

packages/@textlint/kernel/src/task/textlint-core-task.ts, packages/@textlint/types/src/Rule/TextlintFilterRuleModule.ts, packages/@textlint/types/src/Rule/TextlintRuleModule.ts, packages/textlint-tester/test/async-test.ts
Follow below case
```js
module.exports = (context) => {
return {
"my-type"(node){}
}
}
```
=> fix(types): allow other node type for RuleReportHandler

packages/gulp-textlint/CHANGELOG.md, packages/gulp-textlint/package.json
- **deps**: move some dependencies to devDependencies #581 
Thanks to @karak
**All updates**
- gulp-textlint@5.1.3
=> Release gulp-textlint@5.1.3

docs/use-as-modules.md
I think there is no need for this character
=> docs(use-as-modules): remove unnecessary char

packages/textlint/src/config/config.ts, packages/textlint/src/engine/execute-file-backers/cache-backer.ts
In some enviroment(now v2?), does not refer `pacakge.json`.
So, textlint not need to refer package.json when no use `--cache`.
Related issue: https://qiita.com/khsk/items/899f6ea2ccaf947abe1d
fix #597
=> fix(textlint): should not refer `Config#hash` when no use --cache

README.md
Hi, we use `textlint` to keep Cypress' documentation text use consistent. Thanks for your work!
=> Add Cypress docs to README 'who's using textlint'

packages/textlint/src/config/config.ts
Supress following waring on running textlint.
```
(node:68450) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:68450) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:68450) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
```
fix #620
=> fix(textlint): fix crypto's DeprecationWarning

.github/workflows/ci.yml
Ref. #632
Add .github/workflows/ci.yml for GitHub Actions.
As I commented #632 windows environment has some issue, so I dropped windows support.
=> chore(CI): Add GitHub Actions for CI of Linux and macOS

docs/CONTRIBUTING.md, packages/@textlint/markdown-to-ast/package.json, packages/@textlint/markdown-to-ast/src/markdown-parser.js, packages/@textlint/markdown-to-ast/test/fixtures/issue-661-tab-indent-codeblock/input.md, packages/@textlint/markdown-to-ast/test/fixtures/issue-661-tab-indent-codeblock/output.json, yarn.lock
- Normalize rrong `column: -1` to `column: 0`
markdown-to-ast create an invalid AST from following text:
```
* Below are the two types of parameters expected:
* Type `String` called `code`
* Type `boolean` called `accepted`
```
This commit fix to create valid AST.
fix https://github.com/textlint-rule/textlint-rule-no-dead-link/issues/129
fix https://github.com/textlint/textlint/issues/661
=> fix(markdown-to-ast):fix tab + CodeBlock AST

packages/textlint/src/README.md
Fixed some broken links, which seem to be introduced during migration to typescript.
I also found some files referred in the `README.md` no longer exist (e.g. `core/` directory and `rule-manager-js`), but left them untouched as I wasn't sure whether they'd been renamed or just removed.
=> docs(textlint): fix broken link

packages/@textlint/linter-formatter/package.json, packages/@textlint/linter-formatter/src/formatters/pretty-error.ts, yarn.lock
Node.js 8+ supports padStart so that we don't need the  polyfill.
See https://github.com/textlint/textlint/issues/600
=> Drop string.prototype.padstart

docs/integrations.md
Emacs support the syntax check for textlint with the flycheck package
https://www.flycheck.org/en/latest/languages.html#syntax-checker-textlint
=> Add information about emacs texlint support

docs/txtnode.md, packages/@textlint/ast-node-types/src/TypeofTxtNode.ts, packages/@textlint/ast-node-types/src/index.ts, packages/@textlint/markdown-to-ast/src/mapping/markdown-syntax-map.ts, packages/@textlint/markdown-to-ast/test/fixtures/entities-advanced.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/entities.output.entities.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/entities.output.entities=escape.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/entities.output.entities=numbers.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/entities.output.noentities.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/links-title-empty-parentheses.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/links-title-parentheses.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/links-title-unclosed.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/links-url-empty-title-parentheses.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/links-url-mismatched-parentheses.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/links-url-new-line.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/links-url-unclosed.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/links-url-white-space.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/nested-references.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/reference-image-empty-alt.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/reference-link-escape.nooutput.text/output.json, packages/@textlint/markdown-to-ast/test/fixtures/title-attributes.text/output.json, packages/@textlint/markdown-to-ast/tools/create-fixtures.js, packages/@textlint/markdown-to-ast/tools/update-fixtures.js
`ReferenceDef` is the wrong type.
We have deprecated it. It will be removed in the future.
fix https://github.com/textlint/textlint/issues/694
=> fix(ast-node-types): deprecated "ReferenceDef" type

README.md
- Missing https in image path for comparison between PL and NL
=> fix(readme): missing https in image path for comparison between PL and NL

packages/@textlint/textlint-plugin-text/package.json, packages/textlint-tester/test/tsconfig.json, packages/textlint/test/tsconfig.json, tsconfig.base.json, yarn.lock
Enable `--incremental` by default.
Also, TS 4.0 allows `incremental` with `noEmit`.
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#--incremental-with---noemit
It aims to get fast performance.
=> chore: enable TypeScript incremental

packages/@textlint/kernel/src/fixer/source-code-fixer.ts, packages/@textlint/kernel/test/source-code-fixer/source-code-fixer-test.js
Please refer to https://github.com/textlint/textlint/issues/731
The ranges don't overlap when the end of one fix's range is same as start of other fixes' range. 
This PR makes textlint apply all fixes in this condition.
=> fix: make textlint apply adjacent fixes

.github/workflows/ci.yml, packages/@textlint/kernel/src/task/fixer-task.ts
Previously, `getConfigBaseDir()` always return undefined when `textlint --fix`.
fix #741
=> fix(kernel): fix `configBaseDir()` return correct base dir

packages/@textlint/linter-formatter/src/formatters/checkstyle.ts, packages/@textlint/linter-formatter/test/formatters/checkstyle.js
Please refer to #746.
This PR is make escape XML control characters in ruleId.
=> fix(linter-formatter): escape  XML control characters in ruleId

packages/textlint-tester/README.md, packages/textlint-tester/package.json, packages/textlint-tester/src/index.ts, packages/textlint-tester/test/async-test.ts, packages/textlint-tester/test/textlint-tester-fixer-test.ts, packages/textlint-tester/test/textlint-tester-invalid-test.ts, packages/textlint-tester/test/textlint-tester-invalid-testcofig-test.ts, packages/textlint-tester/test/textlint-tester-plugin.ts, packages/textlint-tester/test/textlint-tester-test.ts, packages/textlint-tester/test/tsconfig.json
- use `export default` instead of `export =`
The `textlint-tester` user should use `import` instead of ` require`.
```diff
- const TextLintTester = require("textlint-tester");
+ import TextLintTester from "textlint-tester";
```
of pick `default` property.
```diff
- const TextLintTester = require("textlint-tester");
+ const TextLintTester = require("textlint-tester").default;
```
fix #689
=> fix(textlint-tester): use `export default` instead of `export =`

packages/textlint-scripts/example-ts/package.json, packages/textlint-scripts/example/src/common.js, packages/textlint-scripts/example/src/index.js, packages/textlint-scripts/example/src/module.js, packages/textlint-scripts/example/test/index-test.js, packages/textlint-scripts/package.json, packages/textlint-scripts/test/test-example.js, yarn.lock
Accidentally, 12.0.0 does not include `textlint-scirpts`'s dependencies.
12.0.1 fix  to update`textlint-scripts` dependencies.
fix https://github.com/textlint/textlint/issues/790
=> fix(textlint-scirpts): update to textlint-tester@12

packages/@textlint/linter-formatter/package.json, packages/@textlint/linter-formatter/src/formatters/table.ts, yarn.lock
The npm dependency `table@3.8.3` depends on `ajv@4.11.8` which is vulnerable, see the Snyk report https://snyk.io/test/npm/textlint/12.0.0.
The change consist to update npm dependency table from 3.8.3 to 6.7.1.
=> chore: update npm dependency table from 3.8.3 to 6.7.1

docs/CONTRIBUTING.md, package.json
`husky` was removed from this project in this commit: [Drop to support Node.js 10.x by azu · Pull Request #773 · textlint/textlint](https://github.com/textlint/textlint/pull/773/commits/f25da7e91ff30f473287c9c4d69946f4750bc966#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L43) so I believe we don't need husky related config anymore.
I found a husky-related description in `docs/CONTIRIBUTING.md` and updated it. Also, `npm run prettier` was replaced with `npm run format` by the same commit. I updated that command too.
=> chore: remove the husky config and update the related docs

docs/plugin.md, docs/txtnode.md
Fix typo documentation. 
🙅 `isTextlintAST` is wrong
🙆‍♂️ `isTxtAST` is correct.
https://github.com/textlint/textlint/blob/abb75bb331a5cd563934cce362cea62d6de740ac/packages/%40textlint/ast-tester/src/index.ts#L14
=> Replace isTextlintAST with isTxtAST

packages/@textlint/kernel/src/fixer/fixer-processor.ts, packages/@textlint/kernel/src/linter/linter-processor.ts, packages/@textlint/kernel/src/textlint-kernel.ts, packages/@textlint/kernel/test/helper/AsyncPlugin.ts, packages/@textlint/kernel/test/kernel-plugin-test.ts, packages/@textlint/types/src/Plugin/TextlintPluginModule.ts
- Promise type added to type definition of `preProcess`.
- The method from which preProcess is called is now an `async` function. Fortunately, it was originally a function that returned a Promise, so the change is minimal.
In [textlint-plugin-ruby](https://github.com/alpaca-tc/textlint-plugin-ruby), which I'm developing now, it communicates with the backend ruby process to parse the Ruby source code.
However, since node IO is mainly asynchronous, it is difficult to implement unless preProcess supports the Promise type 😭 
---
By the way, thanks for the replies on [twitter](https://twitter.com/azu_re/status/1465771946675945472?s=20)! 💛
=> Plugin can return Promise when calling preProcess

examples/perf/package.json, packages/textlint/bin/textlint.js, packages/textlint/package.json, yarn.lock
```
❯ yarn audit --groups dependencies
yarn audit v1.22.17
0 vulnerabilities found - Packages audited: 594
✨  Done in 0.95s.
```
all
```
yarn audit
yarn audit v1.22.17
0 vulnerabilities found - Packages audited: 1200
✨  Done in 0.89s.
```
fix #840 
cc @massongit
=> fix(textlint): remove log-symbols 

docs/getting-started.md, website/pages/en/index.js
At the risk of nitpicking, I prefer `npx` introduced in npm 5.2 (released in July 2017) over `./node_modules/.bin/` here.
=> docs: replace `./node_modules/.bin/` with `npx`

packages/@textlint/markdown-to-ast/package.json
pnpm or yarn 2+ require explicit `dependencies`.
fix #903
=> fix(markdown-to-ast): add `mdast-util-gfm-autolink-literal` to explicit deps

website/core/Footer.js
It was linking to the Github homepage
=> Fix Github link in website footer

packages/@textlint/linter-formatter/package.json, yarn.lock
... and removed xml-escape which is not used.
fixes https://github.com/textlint/textlint/issues/933.
=> chore(linter-formatter): added lodash to dependencies

.github/workflows/ci.yml
macOS on GitHub Actions is fragile.
=> CI: remove macOS from matrix

packages/textlint/src/textlint-core.ts, packages/textlint/src/util/find-util.ts, packages/textlint/test/textlint-core/textlint-core-test.ts, packages/textlint/test/util/find-util-test.ts
`path.extname('.lint-todo') === ''`, so we have to be a little smarter than node to capture these files.
With this change, I can now use https://github.com/kellyselden/textlint-rule-eol-last to lint `.lint-todo` files with
```
{
plugins: {
'@textlint/text': {
extensions: ['.lint-todo'],
},
},
rules: {
'eol-last': true,
},
};
```
=> support linting dot files

packages/textlint-tester/package.json, packages/textlint-tester/src/test-util.ts, packages/textlint-tester/src/textlint-tester.ts, packages/textlint-tester/tsconfig.json, packages/textlint/tsconfig.json
- use `@textlint/kernel` for testing
- finally, remove `textlint` dependency 🎉 
fix https://github.com/textlint/textlint/issues/966
=> refactor(textlint-test): use @textlint/kernel

README.md, docs/cli.md, packages/@textlint/fixer-formatter/src/index.ts, packages/textlint/src/cli-new.ts, packages/textlint/src/loader/TextlintrcLoader.ts, packages/textlint/src/options.ts, packages/textlint/test/cli-new/cli-test.ts
- Fix `--no-textlintrc` handling on New CLI #973 
- Add `--print-config` for debug/testing on New CLI
fix https://github.com/textlint/textlint/issues/973
=> feat(textlint): add --print-config flag for New CLI

packages/@textlint/fixer-formatter/src/formatters/compats.ts, packages/@textlint/fixer-formatter/test/formatters/compats-test.js
This PR tries to fix a bug that occurs when the `compats` option is specified for the fixer formatter.
Closes #979
```sh
>>> npm install /Users/sho0628/projects/textlint/packages/@textlint/fixer-formatter /Users/sho0628/projects/textlint/packages/textlint --save-dev
>>> npx textlint file.md --fix --format compats
Fixed✔ /Users/sho0628/projects/textlint_test/file.md: line 2, col 7, Error - Should remove period mark(".") at end of list item. (period-in-list-item)
Fixed 1 problem
```
=> fix(textlint): fix an error on compats fixer formatter

packages/@textlint/kernel/package.json, packages/@textlint/kernel/src/context/TextlintSourceCodeImpl.ts, packages/textlint/package.json, yarn.lock
Update to structured-source@4.
- [Release v4.0.0 · textlint/structured-source](https://github.com/textlint/structured-source/releases/tag/v4.0.0)
fix #983
=> refactor: update to structured-source@4

.github/release.yml, .github/workflows/create-release-pr.yml, .github/workflows/release.yml, docs/CONTRIBUTING.md
A Maintainer release new version of textlint by following way.
1. Create Release PR via GitHub Actions: <https://github.com/textlint/textlint/actions/workflows/create-release-pr.yml>
- Run workflow with `version` input
- You can select new version with semver(patch,minor,major)
2. [CI] Create Release PR
- Update `lerna.json`'s `version` and `packages/*/package.json`'s `version`
- Fill the Pull Request body with [Automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)
- e.g. https://github.com/azu/monorepo-github-releases/pull/18
3. Review the Release PR
- You can modify PR body for changelog
4. Merge the Release PR
5. [CI] Publish new version to npm and GitHub Release
- The release note content is …
=>  CI: add release script 

packages/@textlint/kernel/src/task/promise-event-emitter.ts, packages/@textlint/kernel/src/task/textlint-core-task.ts, packages/@textlint/kernel/src/util/timing.ts
fix https://github.com/textlint/textlint/issues/996
fix https://github.com/textlint/textlint/issues/730
=> refactor(kernel): remove node:events 

docs/txtnode.md, packages/@textlint/ast-node-types/src/ASTNodeTypes.ts, packages/@textlint/ast-node-types/src/NodeType.ts, packages/@textlint/ast-node-types/src/TypeofTxtNode.ts, packages/@textlint/ast-node-types/src/index.ts, packages/@textlint/types/test/Rule/TextlintRuleModule-test.ts, packages/@textlint/types/test/Rule/TxtNode-test.ts
- fix #764 as Breaking Changes
- ref #902 
- fix #740 as Feature
- close #944 - TxtNode is an abstract node that has common property. `children` is not common.
These types are defined in [`@textlint/ast-node-types`](https://github.com/textlint/textlint/tree/master/packages/%40textlint/ast-node-types).
| Type name                       | Node type                        | Description                          |
|---------------------------------|----------------------------------|--------------------------------------|
| ASTNodeTypes.Document           | TxtDocumentNode(TxtParentNode)   | Root Node                            |
| ASTNodeTypes.DocumentExit       | TxtDocumentNode(TxtParentNode)   |                                      |
| ASTNodeTypes.Paragraph          | …
=> feat(ast-node-types): Add individual Node type and Add Table/TableRow/TableCell node 

docs/txtnode.md, packages/@textlint/ast-node-types/src/NodeType.ts, packages/@textlint/ast-node-types/src/index.ts
These are missing exports in v13.
- Rename `TextNodeRange` to `TxtNodeRange`. It is typo
- Rename `TxtNodeLineLocation` to `TxtNodeLocation`.
- export `{ TxtNodeRange, TxtNodeLocation, TxtNodePosition }`
```diff
- import type { TextNodeRange, TxtNodeLineLocation, TxtNodePosition } from "@textlint/ast-node-types";
+ import type { TxtNodeRange, TxtNodeLocation, TxtNodePosition } from "@textlint/ast-node-types";
```
=> fix(ast-node-types): export { TxtNodeRange, TxtNodeLocation, TxtNodePosition }

packages/@textlint/ast-node-types/src/index.ts
Add `TxtNodeType` as public API.
v12 exported it.
=> fix(ast-node-types): export { TxtNodeType }

packages/@textlint/ast-node-types/src/NodeType.ts, packages/@textlint/kernel/src/context/TextlintRuleContextImpl.ts, packages/@textlint/kernel/test/helper/BinaryPlugin.ts, packages/@textlint/kernel/test/source-location/source-location-test.ts, packages/@textlint/markdown-to-ast/src/index.ts, packages/@textlint/markdown-to-ast/src/mapping/markdown-syntax-map.ts, packages/@textlint/text-to-ast/src/plaintext-syntax.ts, packages/@textlint/types/src/Rule/TextlintRuleContext.ts, packages/@textlint/types/src/Rule/TextlintRuleModule.ts, packages/textlint/test/cli/fixtures/fixer-rules/fixer-rule-add.ts, packages/textlint/test/rule-context/rule-context-test.ts
- Correct `type` value in some Nodes
- Remove Markdown Extension from ast-node-types
- Remove `string` from `TxtNodeType`
- It make `TxtNodeType` as `string`
- `_shouldNotUsed` use `never` type
=> fix(ast-node-types): remove markdown extension && fix TxtNodeType

packages/@textlint/ast-node-types/src/NodeType.ts, packages/@textlint/ast-node-types/tsconfig.json, packages/@textlint/types/tsconfig.json
`Node` is DOM Node!
It is wrong type.
- `Node` to `TxtNode` 
- Prevent same mistake by `lib`
=> fix(ast-node-type): fix Node → TxtNode

packages/@textlint/kernel/src/textlint-kernel.ts, packages/textlint/src/cli.ts, packages/textlint/src/createLinter.ts, website/.textlintrc
improve textlint debug log
- add descriptors
- add cliOptions
- simplify process files
```
❯ npx textlint --debug "docs/**" --config ./website/.textlintrc
textlint:cli cliOptions: {"debug":true,"config":"./website/.textlintrc","ignorePath":"/Users/azu/ghq/github.com/textlint/textlint/.textlintignore","init":false,"stdin":false,"format":"stylish","color":true,"quiet":false,"textlintrc":true,"cache":false,"cacheLocation":"/Users/azu/ghq/github.com/textlint/textlint/.textlintcache","_":["docs/**"]} +0ms
textlint:cli textlint --version: 13.1.1 +1ms
textlint:cli Running on files, stdin-filename: undefined +0ms
textlint:cli cliDescriptor: {"rule":[],"filterRule":[],"plugin":[]} +0ms
textlint:cli textlintrcDescriptor: {"rule":[{"ruleId":"eslint","options":{"configFile":"./.eslintrc.js"}},{"ruleId …
```
=> textlint: improve debug log

packages/textlint/package.json
textlint v13 require Node.js 16.0.0>=
fix #1042
=> fix(textlint): Add `engines` to require Node.js 16+

packages/textlint/src/loader/TextlintrcLoader.ts, packages/textlint/test/loadTextlintrc/loadTextlintrc.test.ts
https://github.com/textlint/textlint/pull/1088#issuecomment-1445265820
```
$ cat test.js
const {loadTextlintrc} = require("textlint");
(async function () {
const descriptor = await loadTextlintrc();
})()
$ node test.js
/path/to/node_modules/textlint/lib/src/loader/TextlintrcLoader.js:35
const loadTextlintrc = async ({ configFilePath, node_modulesDir }) => {
^
TypeError: Cannot destructure property 'configFilePath' of 'undefined' as it is undefined.
at loadTextlintrc (/path/to/node_modules/textlint/lib/src/loader/TextlintrcLoader.js:35:33)
at /path/to/test.js:4:30
at Object.<anonymous> (/path/to/test.js:5:3)
at Module._compile (node:internal/modules/cjs/loader:1275:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
at Module.load …
```
=> fix: allow missing parameters for loadTextlintrc

packages/textlint/src/cli.ts, packages/textlint/test/cli/cli-test.ts
This PR attempts to fix to print results when the `--dry-run` option is specified.
fixes: #1091
```sh
>>> echo 'jquery' | npx textlint --fix --dry-run --stdin --stdin-filename test.md --format fixed-result --rule 'textlint-rule-terminology'
jQuery
```
=> fix(textlint): fix to print results when the `--dry-run` option is specified.

docs/use-as-modules.md
I add a semicolon in the README's code since there is code without a semicolon.
=> docs: Add semicolon in code

packages/textlint-scripts/configs/ts-node-register.js, packages/textlint-scripts/package.json
Add `peerDependnecies` to `textlint-scripts`, but it is optional.
=> textlint-scripts: add typescript and ts-node as peerDependencies

package-lock.json, packages/@textlint/linter-formatter/package.json
packages/@textlint/linter-formatter/package.json does not use optionator.
=> chore(deps): remove unused optionator

docs/use-as-modules.md
When I tried this sample code, I did not need `loadFixerFormatter `.So I deleted it.
Also, according to the type definition, `fixText` must require a file path as the second argument, which is correct?
=> loadFixerFormatter is not use in example.

lerna.json, package-lock.json, package.json, tsconfig.json
- Update to lerna 7
- Update to https://github.com/azu/monorepo-utils/releases/tag/v2.10.2
- Remove packages from lerna.json
- It was replaced `packages` in package.json
=> chore: remove packages from lerna.json

docs/txtnode.md, package-lock.json, packages/@textlint/ast-node-types/src/NodeType.ts, packages/@textlint/ast-traverse/src/index.ts, packages/@textlint/ast-traverse/test/txt-traverse-test.ts, packages/@textlint/kernel/test/helper/BinaryPlugin.ts, packages/@textlint/kernel/test/kernel-plugin-test.ts, packages/@textlint/kernel/test/source-location/source-location-test.ts, packages/@textlint/markdown-to-ast/src/index.ts, packages/@textlint/markdown-to-ast/src/parse-markdown.ts, packages/@textlint/markdown-to-ast/test/compliance-tests.ts, packages/@textlint/markdown-to-ast/test/markdown-parser-test.ts, packages/@textlint/text-to-ast/src/plaintext-parser.ts, packages/@textlint/textlint-plugin-text/src/TextProcessor.ts, packages/@textlint/types/src/Plugin/TextlintPluginModule.ts, packages/textlint/test/object-to-kernel-format/fixtures/example-plugin.ts, packages/textlint/test/pluguins/fixtures/example-plugin.ts
This PR fixed types of textlint.
It does not change the behavior of textlint.
- Remove `[index:string]: any;` from `TxtNode`
- Plugin's `preProcess` should return `TxtDocumentNode`
- Previously, it allow return `TxtNode`.
For plugin developer:
You may be necessary to change the type that returns preProcess as follows
```diff
-            preProcess(_text: string, _filePath: string): TxtNode {
+            preProcess(_text: string, _filePath: string): TxtDocumentNode {
```
- fix #1294
=> fix(ast-node-types): remove `[index:string]: any;` from `TxtNode`

packages/@textlint/config-loader/src/TextlintConfigDescriptor.ts, packages/@textlint/config-loader/src/loader.ts, packages/@textlint/config-loader/src/textlint-module-resolver.ts, packages/@textlint/config-loader/test/snapshots/disable-child-rule-of-preset/output.json, packages/@textlint/config-loader/test/snapshots/esm/output.json, packages/@textlint/config-loader/test/snapshots/no-used-rule-will-be-skip-to-load/output.json, packages/@textlint/config-loader/test/snapshots/plguin/output.json, packages/@textlint/config-loader/test/snapshots/preset/output.json, packages/@textlint/config-loader/test/snapshots/ruke-key-should-refer-property-name/output.json, packages/@textlint/config-loader/test/snapshots/scoped-rule/output.json, packages/@textlint/kernel/src/textlint-kernel-interface.ts
This is breaking change, but `@textlint/config-loader` is internal use.
Previously, `moduleName` is a file path.
```diff
{
"type": "RuleInPreset",
"ruleId": "abc/c",
"options": false,
"filePath": "<MODULES_DIR>/textlint-rule-preset-abc/index.js",
-                "moduleName": "<MODULES_DIR>/textlint-rule-preset-abc",
+                "moduleName": "textlint-rule-preset-abc",
"ruleKey": "c"
}
```
```diff
"plugins": [
{
+                "type": "Plugin",
"pluginId": "custom",
"plugin": {},
"filePath": "<MODULES_DIR>/textlint-plugin-custom/index.js",
"moduleName": "textlint-plugin-custom"
}
],
```
Previously, the input module name is not defined in results.
In some usecase, a user want to map input to result.
For this usecase, the user can use inputModuleName <-> moduleName
- …
=> fix(config-loader): enhance config-loader results

packages/textlint/package.json
textlint v14 drops Node.js 16 and requires Node.js 18.x.
This PR updates minimal Node.js version to v18.14.0.
v18.14.0 includes `Buffer.isUtf8` and `os.availableParallelism()`.
These may be required in minor feature.
Close https://github.com/textlint/textlint/issues/1342
=> BREAKING CHANGE: textlint require Node.js v18.14.0>=

packages/@textlint/legacy-textlint-core/README.md, packages/@textlint/legacy-textlint-core/src/index.ts
- `textlint.resetRules()` to initilize setup
Original `TextLintCore` has this one.
=> fix(legacy-textlint-core): add `resetRules()`

package-lock.json, packages/@textlint/fixer-formatter/package.json, packages/@textlint/fixer-formatter/src/index.ts, packages/@textlint/linter-formatter/src/index.ts
- inlining `isFile` function
- remove `is-file` package from dependencies
fix #1361
=> fix(formatter): fix missing `is-file` dependencies

README.md, docs/cli.md
Related: https://github.com/textlint/textlint/pull/1338
=> docs: deprecated `--parallel` and `--max-concurrency` in CLI

website/static/css/custom.css, website/static/css/index.css
=> fix(docs): remove Lato from the documentation website

docs/use-as-modules.md
Added clarity around second argument for linter.lintText. Also added guide for migrating from TextLintEngine to new API.
=> docs(textlint): improve docs for linter.lintText

packages/@textlint/fixer-formatter/src/index.ts, packages/@textlint/linter-formatter/src/index.ts
If textlint is to become a single executable binary in the future, it is important to make it a static import.
- dynamic load is hard to build binary
=> refactor(formatter): import formatter as static

packages/textlint/src/engine/execute-file-backers/cache-backer.ts, packages/textlint/test/cli/cli-test.ts
file-entry-cache throw an error if old cache format exists.
```
Cannot read properties of undefined (reading 'key')
```
=>  fix(textlint): catch file-entry-cache exception 

docs/txtnode.md
Note that if you use this from an earlier version of textlint, it will be `undefined`.
- #1459 
- https://github.com/textlint/textlint/releases/tag/v14.5.0
=> docs: add note about `LinkReference`, `ImageReference` and `Definition`

packages/@textlint/ast-node-types/package.json, packages/@textlint/ast-tester/package.json, packages/@textlint/ast-traverse/package.json, packages/@textlint/config-loader/package.json, packages/@textlint/feature-flag/package.json, packages/@textlint/fixer-formatter/package.json, packages/@textlint/kernel/package.json, packages/@textlint/legacy-textlint-core/package.json, packages/@textlint/linter-formatter/package.json, packages/@textlint/markdown-to-ast/package.json, packages/@textlint/module-interop/package.json, packages/@textlint/source-code-fixer/package.json, packages/@textlint/text-to-ast/package.json, packages/@textlint/textlint-plugin-markdown/package.json, packages/@textlint/textlint-plugin-text/package.json, packages/@textlint/types/package.json, packages/@textlint/utils/package.json, packages/textlint-scripts/package.json, packages/textlint-tester/package.json, packages/textlint/package.json
`require(esm)` misleading current packages.
- fix #1473 
- ref #1472
=> fix: add type=commonjs

packages/@textlint/config-loader/src/config-loader.ts, packages/@textlint/config-loader/test/fixtures/euc-jp.json, packages/@textlint/config-loader/test/fixtures/shift-jis.json, packages/@textlint/config-loader/test/index.test.ts
close https://github.com/textlint/textlint/issues/298
This pull request introduces changes to the `@textlint/config-loader` package to enforce UTF-8 encoding for configuration files.
* [`packages/@textlint/config-loader/src/config-loader.ts`](diffhunk://#diff-ad9621f1e6319b5812853449bf45c8bdc5ba98dd16809a6b2b6777becb88e59bR6-R7): Added UTF-8 encoding validation to ensure that configuration files are encoded in UTF-8 and throw an error if they are not. [[1]](diffhunk://#diff-ad9621f1e6319b5812853449bf45c8bdc5ba98dd16809a6b2b6777becb88e59bR6-R7) [[2]](diffhunk://#diff-ad9621f1e6319b5812853449bf45c8bdc5ba98dd16809a6b2b6777becb88e59bR206-R212)
* [`packages/@textlint/config-loader/test/index.test.ts`](diffhunk://#diff-6ffb1fa27de25171d0c069abd8d9240858eee355ee4ec4715a0e63805feb9a74R58-R81): …
=> feat(config-loader): validate UTF-8 encoding for configuration file

docs/txtnode.md
I discovered this while developing a plugin. I believe that `TxtCodeBlockNode` extends `TxtTextNode`, not `TxtParentNode`[^1].
[^1]: https://github.com/textlint/textlint/blob/master/packages/%40textlint/ast-node-types/src/NodeType.ts#L194-L198
=> docs: correct `TxtCodeBlockNode` node type

README.md
https://github.com/taichi/vscode-textlint is deprecated.
Instead of it, change the link to official fork: https://github.com/textlint/vscode-textlint
Thanks to @taichi!
cc @3w36zj6
=> docs: replace vscode-textlint link

website/siteConfig.js
=> fix(website): use `textlint.org` as domain

.github/workflows/ci.yml, README.md, docs/rule-fixable.md, docs/rule.md, docs/txtnode.md, examples/config-in-package-json/README.md, packages/@textlint/kernel/src/textlint-kernel.ts, packages/@textlint/legacy-textlint-core/README.md, packages/@textlint/markdown-to-ast/README.md, packages/@textlint/text-to-ast/README.md, packages/textlint-scripts/README.md, packages/textlint-tester/README.md, packages/textlint/README.md, packages/textlint/src/DEPRECATED/textfix-engine.ts, packages/textlint/src/DEPRECATED/textlint-core.ts, packages/textlint/src/DEPRECATED/textlint-engine.ts, packages/textlint/src/index.ts, packages/textlint/src/textlint.ts, test/benchmark/README.md, website/blog/2018-05-22-new-website.md, website/blog/2018-07-22-textlint-11.md, website/blog/2023-01-27-textlint-13.md, website/blog/2024-02-03-textlint-14.md, website/pages/en/index.js
=> fix(docs): update links from textlint.github.io to textlint.org

packages/@textlint/kernel/src/descriptor/TextlintPluginDescriptors.ts, packages/@textlint/kernel/test/descriptor/TextlintPluginDescritors-test.ts
close https://github.com/textlint/textlint/issues/623
This pull request updates the logic for matching plugin descriptors by file extensions in the `TextlintPluginDescriptors` class and adds new test cases to validate the changes.
* [`packages/@textlint/kernel/src/descriptor/TextlintPluginDescriptors.ts`](diffhunk://#diff-bfd47c42eb24e8d66c3053c502812a3ae7d20eea2a1475a49affc61161348436L44-R44): Updated the `findPluginDescriptorWithExt` method to use `.some()` for matching extensions, allowing support for multi-part extensions (e.g., `.blade.php`).
* [`packages/@textlint/kernel/test/descriptor/TextlintPluginDescritors-test.ts`](diffhunk://#diff-03e0bc4bf98fefc88bd9dd92e004bf13d0152ac26e22266237faef97e3cf89a2L111-R111): Updated the test description for single extension matching to clarify …
=> feat(kernel): support multi-part extensions in plugin

packages/textlint/src/options.ts
close https://github.com/textlint/textlint/issues/1463
This pull request makes consistent improvements to the descriptions of options in `packages/textlint/src/options.ts` by ensuring all descriptions end with a period.
=> feat(textlint): unify punctuation in CLI option descriptions

package-lock.json, packages/textlint/bin/textlint.js, packages/textlint/package.json
This small PR removes `get-stdin` in favor of built-in `streamConsumers`.
textlint targets Node 18+, stream consumers are available since Node 16.
From `get-stdin` README:
>You can now accomplish this natively in Node.js using [`streamConsumers.text()`](https://nodejs.org/api/>webstreams.html#streamconsumerstextstream) or [`streamConsumers.buffer()`](https://nodejs.org/api/>webstreams.html#streamconsumersbufferstream)
I've run the tests locally, they pass. I used `text()` consumer because `cli.execute` expects a string.
=> refactor: replace get-stdin with built-in stream consumers

README.md, docs/cli.md, package-lock.json, packages/textlint/package.json, packages/textlint/src/DEPRECATED/config.ts, packages/textlint/src/cli.ts, packages/textlint/src/mcp/server.ts, packages/textlint/src/options.ts, packages/textlint/test/cli/cli-test.ts, packages/textlint/test/mcp/fixtures/ok.md, packages/textlint/test/mcp/server.test.ts
This PR is adding `--mcp` option for textlint CLI.
Ref. #1498
I confirmed the behavior with the following steps:
1. Build packages
```
npm run build
```
1. Install `textlint` locally:
```shell
cd packages/textlint/
npm install -g .
```
1. Run MCP Inspector:
```shell
npx -y @modelcontextprotocol/inspector npx textlint --mcp
```
1. Open http://127.0.0.1:6274
1. Click [Connect] and select [LintText]
1. Enter values for text and stdinFilename
1. Click [Run Tool] to execute
=> feat(textlint): add `--mcp` option

docs/mcp.md
The MCP server requires an existing textlint configuration since textlint has no default rules. Updated documentation to clarify this requirement and provide clearer setup instructions.
=> docs(mcp): add configuration prerequisite and improve setup instructions

.github/workflows/create-release-pr.yml, .github/workflows/release.yml
Incorporate a pnpm installation step into the CI release job to streamline the package management process.
=> Add pnpm installation step to release job

netlify.toml, packages/textlint/package.json, packages/textlint/src/DEPRECATED/config.ts, packages/textlint/src/cli.ts, packages/textlint/src/config/config-initializer.ts, packages/textlint/src/createLinter.ts, packages/textlint/src/mcp/server.ts, packages/textlint/test/mcp/server.test.ts, pnpm-lock.yaml
This PR migrates textlint from the deprecated `read-pkg-up` v3 to the modern `read-package-up` v11, while maintaining CommonJS compatibility.
- **Package Migration**: `read-pkg-up` v3 → `read-package-up` v11
- Updated API usage: `pkg` → `packageJson`, `readPkgUpSync` → `readPackageUpSync`
- Used dynamic imports to maintain CJS compatibility
- **MCP Server Refactoring**: Added `setupServer()` function for better test isolation
- Removed global server instance
- Tests can now create/teardown their own server instances
- **Enhanced MCP Compliance**: Improved structured content support (MCP 2025-06-18 specification)
- All tools return both `content` and `structuredContent`
- Proper `isError` flags and enhanced error handling
- **Code Quality**: Made `createLinter` synchronous, moved async …
=> refactor(textlint): use "read-package-up"

.github/workflows/pr-preview.yml, .github/workflows/website-preview.yml, README.md, docs/getting-started.md, docs/plugin.md, docs/rule.md, netlify.toml, website/docusaurus.config.js
This PR replaces Netlify with `pr-preview-action` for PR preview deployments.
- ✅ Removed `netlify.toml` configuration file
- ✅ Added GitHub Actions workflow for PR previews using `pr-preview-action`
- ✅ Only trigger builds when docs or website files are changed
- ✅ Deploy previews to `gh-pages-preview` branch
- ✅ Automatic cleanup when PR is closed
- More reliable than Netlify builds
- Maintenance-free configuration
- Automatic preview cleanup
- No external dependencies
- Integrated with GitHub ecosystem
- Triggers on: `docs/**`, `website/**`, `packages/@textlint/website/**` changes
- Deploy branch: `gh-pages-preview`
- Umbrella directory: `pr-preview`
- Overwrites existing previews (as requested)
Fixes #1579
=> feat: replace Netlify with pr-preview-action

package.json, pnpm-lock.yaml
update eslint-config-prettier from v9 to v10
- <https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md>
=> chore: update eslint-config-prettier from v9 to v10

docs/use-as-modules.md
Updated documentation to include `filterRules` parameter, which is required for `TextlintKernelDescriptor` constructor.
References
- https://github.com/textlint/textlint/blob/3f0423bdfbf136caab71b76d7c0c0e496a03d49e/packages/%40textlint/kernel/src/descriptor/TextlintKernelDescriptor.ts#L17-L23
- https://github.com/textlint/textlint/blob/3f0423bdfbf136caab71b76d7c0c0e496a03d49e/packages/%40textlint/kernel/src/descriptor/README.md?plain=1#L18-L36
=> docs: add filterRules parameter to TextlintKernelDescriptor

website/docusaurus.config.js
New Features:
- Allow the documentation sidebar to be hideable by setting hideable: true in the Docusaurus config
| Before | After |
|--------|--------|
| <img width="2792" height="1738" alt="before" src="https://github.com/user-attachments/assets/cae9fd87-2595-4d65-b1f6-3c9c51349e36" /> | ![after](https://github.com/user-attachments/assets/66eb369b-4c5f-4db3-9bc2-ef462f61a852) |
=> feat(website): make the entire sidebar hideable
